/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false` (hash: 2a6a388f30e4ee9bef0352fb6380bd53)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Sandbox" | "AgentDO" | "ChatSubAgent" | "IssueRunSubAgent" | "AutomationTriggerDO";
	}
	interface ProductionEnv {
		BROWSER: Fetcher;
		DATABASE_URL: string;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		ENVIRONMENT: string;
		GITHUB_APP_ID: string;
		GITHUB_APP_SLUG: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		GITHUB_APP_PRIVATE_KEY: string;
		GITHUB_WEBHOOK_SECRET: string;
		CF_AIG_TOKEN: string;
		AgentDO: DurableObjectNamespace<import("./src/server").AgentDO>;
		Sandbox: DurableObjectNamespace<import("./src/server").Sandbox>;
		AUTOMATION_TRIGGER: DurableObjectNamespace<import("./src/server").AutomationTriggerDO>;
		MCP_SESSION: DurableObjectNamespace /* McpProxySession from garden-mcp-proxy */;
		MCP_PROXY: Fetcher /* garden-mcp-proxy */;
		RUN_WORKFLOW: Workflow<Parameters<import("./src/server").RunWorkflow['run']>[0]['payload']>;
	}
	interface Env {
		BROWSER: Fetcher;
		DATABASE_URL: string;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		ENVIRONMENT: string;
		GITHUB_APP_ID: string;
		GITHUB_APP_SLUG: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		GITHUB_APP_PRIVATE_KEY: string;
		GITHUB_WEBHOOK_SECRET: string;
		CF_AIG_TOKEN: string;
		AgentDO: DurableObjectNamespace<import("./src/server").AgentDO>;
		Sandbox: DurableObjectNamespace<import("./src/server").Sandbox>;
		AUTOMATION_TRIGGER: DurableObjectNamespace<import("./src/server").AutomationTriggerDO>;
		MCP_SESSION: DurableObjectNamespace /* McpProxySession from garden-mcp-proxy */;
		MCP_PROXY: Fetcher /* garden-mcp-proxy */;
		RUN_WORKFLOW: Workflow<Parameters<import("./src/server").RunWorkflow['run']>[0]['payload']>;
		FILES?: R2Bucket;
		LOADER?: WorkerLoader;
		SANDBOX_TRANSPORT?: "websocket";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "CLOUDFLARE_ACCOUNT_ID" | "ENVIRONMENT" | "GITHUB_APP_ID" | "GITHUB_APP_SLUG" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "GITHUB_APP_PRIVATE_KEY" | "GITHUB_WEBHOOK_SECRET" | "CF_AIG_TOKEN" | "SANDBOX_TRANSPORT">> {}
}
