/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=../../.env.example --include-runtime=false` (hash: 46f3f1e804b66a47f01b16b3b36993d2)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	EXECUTOR_BLOBS: R2Bucket;
	EXECUTOR_DB: D1Database;
	HYPERDRIVE: Hyperdrive;
	EMAIL: SendEmail;
	LOADER: WorkerLoader;
	BROWSER: BrowserRun;
	AI: Ai;
	SANDBOX_TRANSPORT: "rpc";
	SANDBOX_LOG_LEVEL: "warn";
	GARDEN_LOG_LEVEL: "warn";
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	DATABASE_URL: string;
	ENVIRONMENT: string;
	EXECUTOR_SECRET_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	AgentDO: DurableObjectNamespace<import("./src/server").AgentDO>;
	Sandbox: DurableObjectNamespace<import("./src/server").Sandbox>;
	AUTOMATION_TRIGGER: DurableObjectNamespace<import("./src/server").AutomationTriggerDO>;
	EXECUTOR_MCP_SESSION: DurableObjectNamespace<import("./src/server").ExecutorMcpSession>;
	EXECUTOR_MCP_EXECUTION_OWNER: DurableObjectNamespace<import("./src/server").ExecutorMcpExecutionOwnerDirectory>;
	RUN_WORKFLOW: Workflow<Parameters<import("./src/server").RunWorkflow['run']>[0]['payload']>;
	MAIL_DELIVERY_WORKFLOW: Workflow<Parameters<import("./src/server").MailDeliveryWorkflow['run']>[0]['payload']>;
	GMAIL_IMPORT_WORKFLOW: Workflow<Parameters<import("./src/server").GmailImportWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Sandbox" | "AgentDO" | "ChatSubAgent" | "IssueRunSubAgent" | "AutomationTriggerDO" | "ExecutorMcpSession" | "ExecutorMcpExecutionOwnerDirectory";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SANDBOX_TRANSPORT" | "SANDBOX_LOG_LEVEL" | "GARDEN_LOG_LEVEL" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "DATABASE_URL" | "ENVIRONMENT" | "EXECUTOR_SECRET_KEY" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET">> {}
}
