/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkspacesRouteImport } from './routes/api/workspaces'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiRuntimesRouteImport } from './routes/api/runtimes'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiIssuesRouteImport } from './routes/api/issues'
import { Route as ApiInvitationsRouteImport } from './routes/api/invitations'
import { Route as ApiInboxRouteImport } from './routes/api/inbox'
import { Route as ApiDebugStreamRouteImport } from './routes/api/debug-stream'
import { Route as ApiConnectionsRouteImport } from './routes/api/connections'
import { Route as ApiAutomationsRouteImport } from './routes/api/automations'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedAutomationsIndexRouteImport } from './routes/_authenticated/automations/index'
import { Route as ApiWorkspacesIdRouteImport } from './routes/api/workspaces/$id'
import { Route as ApiSkillsSearchRouteImport } from './routes/api/skills/search'
import { Route as ApiSkillsPreviewRouteImport } from './routes/api/skills/preview'
import { Route as ApiSkillsImportRouteImport } from './routes/api/skills/import'
import { Route as ApiSkillsIdRouteImport } from './routes/api/skills/$id'
import { Route as ApiRunsIdRouteImport } from './routes/api/runs/$id'
import { Route as ApiIssuesSearchRouteImport } from './routes/api/issues/search'
import { Route as ApiIssuesChildProgressRouteImport } from './routes/api/issues/child-progress'
import { Route as ApiIssuesIdRouteImport } from './routes/api/issues/$id'
import { Route as ApiInvitationsIdRouteImport } from './routes/api/invitations/$id'
import { Route as ApiInternalCapabilitySyncRouteImport } from './routes/api/internal/capability-sync'
import { Route as ApiInboxUnreadCountRouteImport } from './routes/api/inbox/unread-count'
import { Route as ApiInboxMarkAllReadRouteImport } from './routes/api/inbox/mark-all-read'
import { Route as ApiInboxArchiveCompletedRouteImport } from './routes/api/inbox/archive-completed'
import { Route as ApiInboxArchiveAllReadRouteImport } from './routes/api/inbox/archive-all-read'
import { Route as ApiInboxArchiveAllRouteImport } from './routes/api/inbox/archive-all'
import { Route as ApiGithubSetupRouteImport } from './routes/api/github/setup'
import { Route as ApiGithubInstallRouteImport } from './routes/api/github/install'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github/callback'
import { Route as ApiDevIssueRunPlanRouteImport } from './routes/api/dev/issue-run-plan'
import { Route as ApiConnectionsConnectorIdRouteImport } from './routes/api/connections/$connectorId'
import { Route as ApiCommentsIdRouteImport } from './routes/api/comments/$id'
import { Route as ApiChatThreadsRouteImport } from './routes/api/chat/threads'
import { Route as ApiAutomationsIdRouteImport } from './routes/api/automations/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentsIdRouteImport } from './routes/api/agents/$id'
import { Route as AuthenticatedAutomationsIdRouteImport } from './routes/_authenticated/automations/$id'
import { Route as ApiWorkspacesIdMembersRouteImport } from './routes/api/workspaces/$id/members'
import { Route as ApiWorkspacesIdInvitationsRouteImport } from './routes/api/workspaces/$id/invitations'
import { Route as ApiWorkProductsIdReviewRouteImport } from './routes/api/work-products/$id/review'
import { Route as ApiPermissionRequestsIdResolveRouteImport } from './routes/api/permission-requests/$id/resolve'
import { Route as ApiIssuesIdWorkProductsRouteImport } from './routes/api/issues/$id/work-products'
import { Route as ApiIssuesIdUsageRouteImport } from './routes/api/issues/$id/usage'
import { Route as ApiIssuesIdUnsubscribeRouteImport } from './routes/api/issues/$id/unsubscribe'
import { Route as ApiIssuesIdTimelineRouteImport } from './routes/api/issues/$id/timeline'
import { Route as ApiIssuesIdSubscribersRouteImport } from './routes/api/issues/$id/subscribers'
import { Route as ApiIssuesIdSubscribeRouteImport } from './routes/api/issues/$id/subscribe'
import { Route as ApiIssuesIdSourceBindingsRouteImport } from './routes/api/issues/$id/source-bindings'
import { Route as ApiIssuesIdRunsRouteImport } from './routes/api/issues/$id/runs'
import { Route as ApiIssuesIdReactionsRouteImport } from './routes/api/issues/$id/reactions'
import { Route as ApiIssuesIdEventsRouteImport } from './routes/api/issues/$id/events'
import { Route as ApiIssuesIdCommentsRouteImport } from './routes/api/issues/$id/comments'
import { Route as ApiIssuesIdCancelRouteImport } from './routes/api/issues/$id/cancel'
import { Route as ApiIssuesIdActiveRunRouteImport } from './routes/api/issues/$id/active-run'
import { Route as ApiInvitationsIdDeclineRouteImport } from './routes/api/invitations/$id/decline'
import { Route as ApiInvitationsIdAcceptRouteImport } from './routes/api/invitations/$id/accept'
import { Route as ApiInboxIdReadRouteImport } from './routes/api/inbox/$id/read'
import { Route as ApiInboxIdArchiveRouteImport } from './routes/api/inbox/$id/archive'
import { Route as ApiDocumentsIdVersionsRouteImport } from './routes/api/documents/$id/versions'
import { Route as ApiDocumentsIdTrackedChangeIdsRouteImport } from './routes/api/documents/$id/tracked-change-ids'
import { Route as ApiDocumentsIdMetadataRouteImport } from './routes/api/documents/$id/metadata'
import { Route as ApiDocumentsIdDocxRouteImport } from './routes/api/documents/$id/docx'
import { Route as ApiDocumentsIdDisplayRouteImport } from './routes/api/documents/$id/display'
import { Route as ApiConnectionsConnectorIdActivityRouteImport } from './routes/api/connections/$connectorId/activity'
import { Route as ApiCommentsIdReactionsRouteImport } from './routes/api/comments/$id/reactions'
import { Route as ApiChatThreadsIdRouteImport } from './routes/api/chat/threads/$id'
import { Route as ApiAutomationsIdTriggersRouteImport } from './routes/api/automations/$id/triggers'
import { Route as ApiAutomationsIdTriggerRouteImport } from './routes/api/automations/$id/trigger'
import { Route as ApiAutomationsIdRunsRouteImport } from './routes/api/automations/$id/runs'
import { Route as ApiAgentsIdSkillsRouteImport } from './routes/api/agents/$id/skills'
import { Route as ApiAgentsIdRestoreRouteImport } from './routes/api/agents/$id/restore'
import { Route as ApiAgentsIdArchiveRouteImport } from './routes/api/agents/$id/archive'
import { Route as ApiWorkspacesIdMembersMemberIdRouteImport } from './routes/api/workspaces/$id/members/$memberId'
import { Route as ApiWorkspacesIdInvitationsInvitationIdRouteImport } from './routes/api/workspaces/$id/invitations/$invitationId'
import { Route as ApiIssuesIdSourceBindingsBindingIdRouteImport } from './routes/api/issues/$id/source-bindings/$bindingId'
import { Route as ApiChatThreadsIdToolApprovalRouteImport } from './routes/api/chat/threads/$id/tool-approval'
import { Route as ApiChatThreadsIdPrimaryIssueRouteImport } from './routes/api/chat/threads/$id/primary-issue'
import { Route as ApiChatThreadsIdDocumentsRouteImport } from './routes/api/chat/threads/$id/documents'
import { Route as ApiAutomationsIdTriggersTriggerIdRouteImport } from './routes/api/automations/$id/triggers/$triggerId'
import { Route as ApiDocumentsDocumentIdEditsEditIdActionRouteImport } from './routes/api/documents/$documentId/edits/$editId/$action'
import { Route as ApiConnectionsConnectorIdToolsNameGrantRouteImport } from './routes/api/connections/$connectorId/tools/$name/grant'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesRoute = ApiWorkspacesRouteImport.update({
  id: '/api/workspaces',
  path: '/api/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimesRoute = ApiRuntimesRouteImport.update({
  id: '/api/runtimes',
  path: '/api/runtimes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIssuesRoute = ApiIssuesRouteImport.update({
  id: '/api/issues',
  path: '/api/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsRoute = ApiInvitationsRouteImport.update({
  id: '/api/invitations',
  path: '/api/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugStreamRoute = ApiDebugStreamRouteImport.update({
  id: '/api/debug-stream',
  path: '/api/debug-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsRoute = ApiConnectionsRouteImport.update({
  id: '/api/connections',
  path: '/api/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationsRoute = ApiAutomationsRouteImport.update({
  id: '/api/automations',
  path: '/api/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationsIndexRoute =
  AuthenticatedAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiWorkspacesIdRoute = ApiWorkspacesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWorkspacesRoute,
} as any)
const ApiSkillsSearchRoute = ApiSkillsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsPreviewRoute = ApiSkillsPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsImportRoute = ApiSkillsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsIdRoute = ApiSkillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiRunsIdRoute = ApiRunsIdRouteImport.update({
  id: '/api/runs/$id',
  path: '/api/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIssuesSearchRoute = ApiIssuesSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiIssuesChildProgressRoute = ApiIssuesChildProgressRouteImport.update({
  id: '/child-progress',
  path: '/child-progress',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiIssuesIdRoute = ApiIssuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiInvitationsIdRoute = ApiInvitationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvitationsRoute,
} as any)
const ApiInternalCapabilitySyncRoute =
  ApiInternalCapabilitySyncRouteImport.update({
    id: '/api/internal/capability-sync',
    path: '/api/internal/capability-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInboxUnreadCountRoute = ApiInboxUnreadCountRouteImport.update({
  id: '/unread-count',
  path: '/unread-count',
  getParentRoute: () => ApiInboxRoute,
} as any)
const ApiInboxMarkAllReadRoute = ApiInboxMarkAllReadRouteImport.update({
  id: '/mark-all-read',
  path: '/mark-all-read',
  getParentRoute: () => ApiInboxRoute,
} as any)
const ApiInboxArchiveCompletedRoute =
  ApiInboxArchiveCompletedRouteImport.update({
    id: '/archive-completed',
    path: '/archive-completed',
    getParentRoute: () => ApiInboxRoute,
  } as any)
const ApiInboxArchiveAllReadRoute = ApiInboxArchiveAllReadRouteImport.update({
  id: '/archive-all-read',
  path: '/archive-all-read',
  getParentRoute: () => ApiInboxRoute,
} as any)
const ApiInboxArchiveAllRoute = ApiInboxArchiveAllRouteImport.update({
  id: '/archive-all',
  path: '/archive-all',
  getParentRoute: () => ApiInboxRoute,
} as any)
const ApiGithubSetupRoute = ApiGithubSetupRouteImport.update({
  id: '/api/github/setup',
  path: '/api/github/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallRoute = ApiGithubInstallRouteImport.update({
  id: '/api/github/install',
  path: '/api/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevIssueRunPlanRoute = ApiDevIssueRunPlanRouteImport.update({
  id: '/api/dev/issue-run-plan',
  path: '/api/dev/issue-run-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsConnectorIdRoute =
  ApiConnectionsConnectorIdRouteImport.update({
    id: '/$connectorId',
    path: '/$connectorId',
    getParentRoute: () => ApiConnectionsRoute,
  } as any)
const ApiCommentsIdRoute = ApiCommentsIdRouteImport.update({
  id: '/api/comments/$id',
  path: '/api/comments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatThreadsRoute = ApiChatThreadsRouteImport.update({
  id: '/api/chat/threads',
  path: '/api/chat/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationsIdRoute = ApiAutomationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAutomationsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIdRoute = ApiAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAgentsRoute,
} as any)
const AuthenticatedAutomationsIdRoute =
  AuthenticatedAutomationsIdRouteImport.update({
    id: '/automations/$id',
    path: '/automations/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiWorkspacesIdMembersRoute = ApiWorkspacesIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiWorkspacesIdRoute,
} as any)
const ApiWorkspacesIdInvitationsRoute =
  ApiWorkspacesIdInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => ApiWorkspacesIdRoute,
  } as any)
const ApiWorkProductsIdReviewRoute = ApiWorkProductsIdReviewRouteImport.update({
  id: '/api/work-products/$id/review',
  path: '/api/work-products/$id/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPermissionRequestsIdResolveRoute =
  ApiPermissionRequestsIdResolveRouteImport.update({
    id: '/api/permission-requests/$id/resolve',
    path: '/api/permission-requests/$id/resolve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIssuesIdWorkProductsRoute = ApiIssuesIdWorkProductsRouteImport.update({
  id: '/work-products',
  path: '/work-products',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdUsageRoute = ApiIssuesIdUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdUnsubscribeRoute = ApiIssuesIdUnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdTimelineRoute = ApiIssuesIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdSubscribersRoute = ApiIssuesIdSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdSubscribeRoute = ApiIssuesIdSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdSourceBindingsRoute =
  ApiIssuesIdSourceBindingsRouteImport.update({
    id: '/source-bindings',
    path: '/source-bindings',
    getParentRoute: () => ApiIssuesIdRoute,
  } as any)
const ApiIssuesIdRunsRoute = ApiIssuesIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdReactionsRoute = ApiIssuesIdReactionsRouteImport.update({
  id: '/reactions',
  path: '/reactions',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdEventsRoute = ApiIssuesIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdCommentsRoute = ApiIssuesIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdCancelRoute = ApiIssuesIdCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdActiveRunRoute = ApiIssuesIdActiveRunRouteImport.update({
  id: '/active-run',
  path: '/active-run',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiInvitationsIdDeclineRoute = ApiInvitationsIdDeclineRouteImport.update({
  id: '/decline',
  path: '/decline',
  getParentRoute: () => ApiInvitationsIdRoute,
} as any)
const ApiInvitationsIdAcceptRoute = ApiInvitationsIdAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => ApiInvitationsIdRoute,
} as any)
const ApiInboxIdReadRoute = ApiInboxIdReadRouteImport.update({
  id: '/$id/read',
  path: '/$id/read',
  getParentRoute: () => ApiInboxRoute,
} as any)
const ApiInboxIdArchiveRoute = ApiInboxIdArchiveRouteImport.update({
  id: '/$id/archive',
  path: '/$id/archive',
  getParentRoute: () => ApiInboxRoute,
} as any)
const ApiDocumentsIdVersionsRoute = ApiDocumentsIdVersionsRouteImport.update({
  id: '/api/documents/$id/versions',
  path: '/api/documents/$id/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsIdTrackedChangeIdsRoute =
  ApiDocumentsIdTrackedChangeIdsRouteImport.update({
    id: '/api/documents/$id/tracked-change-ids',
    path: '/api/documents/$id/tracked-change-ids',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsIdMetadataRoute = ApiDocumentsIdMetadataRouteImport.update({
  id: '/api/documents/$id/metadata',
  path: '/api/documents/$id/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsIdDocxRoute = ApiDocumentsIdDocxRouteImport.update({
  id: '/api/documents/$id/docx',
  path: '/api/documents/$id/docx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsIdDisplayRoute = ApiDocumentsIdDisplayRouteImport.update({
  id: '/api/documents/$id/display',
  path: '/api/documents/$id/display',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsConnectorIdActivityRoute =
  ApiConnectionsConnectorIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ApiConnectionsConnectorIdRoute,
  } as any)
const ApiCommentsIdReactionsRoute = ApiCommentsIdReactionsRouteImport.update({
  id: '/reactions',
  path: '/reactions',
  getParentRoute: () => ApiCommentsIdRoute,
} as any)
const ApiChatThreadsIdRoute = ApiChatThreadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiChatThreadsRoute,
} as any)
const ApiAutomationsIdTriggersRoute =
  ApiAutomationsIdTriggersRouteImport.update({
    id: '/triggers',
    path: '/triggers',
    getParentRoute: () => ApiAutomationsIdRoute,
  } as any)
const ApiAutomationsIdTriggerRoute = ApiAutomationsIdTriggerRouteImport.update({
  id: '/trigger',
  path: '/trigger',
  getParentRoute: () => ApiAutomationsIdRoute,
} as any)
const ApiAutomationsIdRunsRoute = ApiAutomationsIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ApiAutomationsIdRoute,
} as any)
const ApiAgentsIdSkillsRoute = ApiAgentsIdSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ApiAgentsIdRoute,
} as any)
const ApiAgentsIdRestoreRoute = ApiAgentsIdRestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => ApiAgentsIdRoute,
} as any)
const ApiAgentsIdArchiveRoute = ApiAgentsIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ApiAgentsIdRoute,
} as any)
const ApiWorkspacesIdMembersMemberIdRoute =
  ApiWorkspacesIdMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => ApiWorkspacesIdMembersRoute,
  } as any)
const ApiWorkspacesIdInvitationsInvitationIdRoute =
  ApiWorkspacesIdInvitationsInvitationIdRouteImport.update({
    id: '/$invitationId',
    path: '/$invitationId',
    getParentRoute: () => ApiWorkspacesIdInvitationsRoute,
  } as any)
const ApiIssuesIdSourceBindingsBindingIdRoute =
  ApiIssuesIdSourceBindingsBindingIdRouteImport.update({
    id: '/$bindingId',
    path: '/$bindingId',
    getParentRoute: () => ApiIssuesIdSourceBindingsRoute,
  } as any)
const ApiChatThreadsIdToolApprovalRoute =
  ApiChatThreadsIdToolApprovalRouteImport.update({
    id: '/tool-approval',
    path: '/tool-approval',
    getParentRoute: () => ApiChatThreadsIdRoute,
  } as any)
const ApiChatThreadsIdPrimaryIssueRoute =
  ApiChatThreadsIdPrimaryIssueRouteImport.update({
    id: '/primary-issue',
    path: '/primary-issue',
    getParentRoute: () => ApiChatThreadsIdRoute,
  } as any)
const ApiChatThreadsIdDocumentsRoute =
  ApiChatThreadsIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ApiChatThreadsIdRoute,
  } as any)
const ApiAutomationsIdTriggersTriggerIdRoute =
  ApiAutomationsIdTriggersTriggerIdRouteImport.update({
    id: '/$triggerId',
    path: '/$triggerId',
    getParentRoute: () => ApiAutomationsIdTriggersRoute,
  } as any)
const ApiDocumentsDocumentIdEditsEditIdActionRoute =
  ApiDocumentsDocumentIdEditsEditIdActionRouteImport.update({
    id: '/api/documents/$documentId/edits/$editId/$action',
    path: '/api/documents/$documentId/edits/$editId/$action',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConnectionsConnectorIdToolsNameGrantRoute =
  ApiConnectionsConnectorIdToolsNameGrantRouteImport.update({
    id: '/tools/$name/grant',
    path: '/tools/$name/grant',
    getParentRoute: () => ApiConnectionsConnectorIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/automations': typeof ApiAutomationsRouteWithChildren
  '/api/connections': typeof ApiConnectionsRouteWithChildren
  '/api/debug-stream': typeof ApiDebugStreamRoute
  '/api/inbox': typeof ApiInboxRouteWithChildren
  '/api/invitations': typeof ApiInvitationsRouteWithChildren
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/runtimes': typeof ApiRuntimesRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/automations/$id': typeof AuthenticatedAutomationsIdRoute
  '/api/agents/$id': typeof ApiAgentsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/automations/$id': typeof ApiAutomationsIdRouteWithChildren
  '/api/chat/threads': typeof ApiChatThreadsRouteWithChildren
  '/api/comments/$id': typeof ApiCommentsIdRouteWithChildren
  '/api/connections/$connectorId': typeof ApiConnectionsConnectorIdRouteWithChildren
  '/api/dev/issue-run-plan': typeof ApiDevIssueRunPlanRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/inbox/archive-all': typeof ApiInboxArchiveAllRoute
  '/api/inbox/archive-all-read': typeof ApiInboxArchiveAllReadRoute
  '/api/inbox/archive-completed': typeof ApiInboxArchiveCompletedRoute
  '/api/inbox/mark-all-read': typeof ApiInboxMarkAllReadRoute
  '/api/inbox/unread-count': typeof ApiInboxUnreadCountRoute
  '/api/internal/capability-sync': typeof ApiInternalCapabilitySyncRoute
  '/api/invitations/$id': typeof ApiInvitationsIdRouteWithChildren
  '/api/issues/$id': typeof ApiIssuesIdRouteWithChildren
  '/api/issues/child-progress': typeof ApiIssuesChildProgressRoute
  '/api/issues/search': typeof ApiIssuesSearchRoute
  '/api/runs/$id': typeof ApiRunsIdRoute
  '/api/skills/$id': typeof ApiSkillsIdRoute
  '/api/skills/import': typeof ApiSkillsImportRoute
  '/api/skills/preview': typeof ApiSkillsPreviewRoute
  '/api/skills/search': typeof ApiSkillsSearchRoute
  '/api/workspaces/$id': typeof ApiWorkspacesIdRouteWithChildren
  '/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/api/agents/$id/archive': typeof ApiAgentsIdArchiveRoute
  '/api/agents/$id/restore': typeof ApiAgentsIdRestoreRoute
  '/api/agents/$id/skills': typeof ApiAgentsIdSkillsRoute
  '/api/automations/$id/runs': typeof ApiAutomationsIdRunsRoute
  '/api/automations/$id/trigger': typeof ApiAutomationsIdTriggerRoute
  '/api/automations/$id/triggers': typeof ApiAutomationsIdTriggersRouteWithChildren
  '/api/chat/threads/$id': typeof ApiChatThreadsIdRouteWithChildren
  '/api/comments/$id/reactions': typeof ApiCommentsIdReactionsRoute
  '/api/connections/$connectorId/activity': typeof ApiConnectionsConnectorIdActivityRoute
  '/api/documents/$id/display': typeof ApiDocumentsIdDisplayRoute
  '/api/documents/$id/docx': typeof ApiDocumentsIdDocxRoute
  '/api/documents/$id/metadata': typeof ApiDocumentsIdMetadataRoute
  '/api/documents/$id/tracked-change-ids': typeof ApiDocumentsIdTrackedChangeIdsRoute
  '/api/documents/$id/versions': typeof ApiDocumentsIdVersionsRoute
  '/api/inbox/$id/archive': typeof ApiInboxIdArchiveRoute
  '/api/inbox/$id/read': typeof ApiInboxIdReadRoute
  '/api/invitations/$id/accept': typeof ApiInvitationsIdAcceptRoute
  '/api/invitations/$id/decline': typeof ApiInvitationsIdDeclineRoute
  '/api/issues/$id/active-run': typeof ApiIssuesIdActiveRunRoute
  '/api/issues/$id/cancel': typeof ApiIssuesIdCancelRoute
  '/api/issues/$id/comments': typeof ApiIssuesIdCommentsRoute
  '/api/issues/$id/events': typeof ApiIssuesIdEventsRoute
  '/api/issues/$id/reactions': typeof ApiIssuesIdReactionsRoute
  '/api/issues/$id/runs': typeof ApiIssuesIdRunsRoute
  '/api/issues/$id/source-bindings': typeof ApiIssuesIdSourceBindingsRouteWithChildren
  '/api/issues/$id/subscribe': typeof ApiIssuesIdSubscribeRoute
  '/api/issues/$id/subscribers': typeof ApiIssuesIdSubscribersRoute
  '/api/issues/$id/timeline': typeof ApiIssuesIdTimelineRoute
  '/api/issues/$id/unsubscribe': typeof ApiIssuesIdUnsubscribeRoute
  '/api/issues/$id/usage': typeof ApiIssuesIdUsageRoute
  '/api/issues/$id/work-products': typeof ApiIssuesIdWorkProductsRoute
  '/api/permission-requests/$id/resolve': typeof ApiPermissionRequestsIdResolveRoute
  '/api/work-products/$id/review': typeof ApiWorkProductsIdReviewRoute
  '/api/workspaces/$id/invitations': typeof ApiWorkspacesIdInvitationsRouteWithChildren
  '/api/workspaces/$id/members': typeof ApiWorkspacesIdMembersRouteWithChildren
  '/api/automations/$id/triggers/$triggerId': typeof ApiAutomationsIdTriggersTriggerIdRoute
  '/api/chat/threads/$id/documents': typeof ApiChatThreadsIdDocumentsRoute
  '/api/chat/threads/$id/primary-issue': typeof ApiChatThreadsIdPrimaryIssueRoute
  '/api/chat/threads/$id/tool-approval': typeof ApiChatThreadsIdToolApprovalRoute
  '/api/issues/$id/source-bindings/$bindingId': typeof ApiIssuesIdSourceBindingsBindingIdRoute
  '/api/workspaces/$id/invitations/$invitationId': typeof ApiWorkspacesIdInvitationsInvitationIdRoute
  '/api/workspaces/$id/members/$memberId': typeof ApiWorkspacesIdMembersMemberIdRoute
  '/api/connections/$connectorId/tools/$name/grant': typeof ApiConnectionsConnectorIdToolsNameGrantRoute
  '/api/documents/$documentId/edits/$editId/$action': typeof ApiDocumentsDocumentIdEditsEditIdActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/automations': typeof ApiAutomationsRouteWithChildren
  '/api/connections': typeof ApiConnectionsRouteWithChildren
  '/api/debug-stream': typeof ApiDebugStreamRoute
  '/api/inbox': typeof ApiInboxRouteWithChildren
  '/api/invitations': typeof ApiInvitationsRouteWithChildren
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/runtimes': typeof ApiRuntimesRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/automations/$id': typeof AuthenticatedAutomationsIdRoute
  '/api/agents/$id': typeof ApiAgentsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/automations/$id': typeof ApiAutomationsIdRouteWithChildren
  '/api/chat/threads': typeof ApiChatThreadsRouteWithChildren
  '/api/comments/$id': typeof ApiCommentsIdRouteWithChildren
  '/api/connections/$connectorId': typeof ApiConnectionsConnectorIdRouteWithChildren
  '/api/dev/issue-run-plan': typeof ApiDevIssueRunPlanRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/inbox/archive-all': typeof ApiInboxArchiveAllRoute
  '/api/inbox/archive-all-read': typeof ApiInboxArchiveAllReadRoute
  '/api/inbox/archive-completed': typeof ApiInboxArchiveCompletedRoute
  '/api/inbox/mark-all-read': typeof ApiInboxMarkAllReadRoute
  '/api/inbox/unread-count': typeof ApiInboxUnreadCountRoute
  '/api/internal/capability-sync': typeof ApiInternalCapabilitySyncRoute
  '/api/invitations/$id': typeof ApiInvitationsIdRouteWithChildren
  '/api/issues/$id': typeof ApiIssuesIdRouteWithChildren
  '/api/issues/child-progress': typeof ApiIssuesChildProgressRoute
  '/api/issues/search': typeof ApiIssuesSearchRoute
  '/api/runs/$id': typeof ApiRunsIdRoute
  '/api/skills/$id': typeof ApiSkillsIdRoute
  '/api/skills/import': typeof ApiSkillsImportRoute
  '/api/skills/preview': typeof ApiSkillsPreviewRoute
  '/api/skills/search': typeof ApiSkillsSearchRoute
  '/api/workspaces/$id': typeof ApiWorkspacesIdRouteWithChildren
  '/automations': typeof AuthenticatedAutomationsIndexRoute
  '/api/agents/$id/archive': typeof ApiAgentsIdArchiveRoute
  '/api/agents/$id/restore': typeof ApiAgentsIdRestoreRoute
  '/api/agents/$id/skills': typeof ApiAgentsIdSkillsRoute
  '/api/automations/$id/runs': typeof ApiAutomationsIdRunsRoute
  '/api/automations/$id/trigger': typeof ApiAutomationsIdTriggerRoute
  '/api/automations/$id/triggers': typeof ApiAutomationsIdTriggersRouteWithChildren
  '/api/chat/threads/$id': typeof ApiChatThreadsIdRouteWithChildren
  '/api/comments/$id/reactions': typeof ApiCommentsIdReactionsRoute
  '/api/connections/$connectorId/activity': typeof ApiConnectionsConnectorIdActivityRoute
  '/api/documents/$id/display': typeof ApiDocumentsIdDisplayRoute
  '/api/documents/$id/docx': typeof ApiDocumentsIdDocxRoute
  '/api/documents/$id/metadata': typeof ApiDocumentsIdMetadataRoute
  '/api/documents/$id/tracked-change-ids': typeof ApiDocumentsIdTrackedChangeIdsRoute
  '/api/documents/$id/versions': typeof ApiDocumentsIdVersionsRoute
  '/api/inbox/$id/archive': typeof ApiInboxIdArchiveRoute
  '/api/inbox/$id/read': typeof ApiInboxIdReadRoute
  '/api/invitations/$id/accept': typeof ApiInvitationsIdAcceptRoute
  '/api/invitations/$id/decline': typeof ApiInvitationsIdDeclineRoute
  '/api/issues/$id/active-run': typeof ApiIssuesIdActiveRunRoute
  '/api/issues/$id/cancel': typeof ApiIssuesIdCancelRoute
  '/api/issues/$id/comments': typeof ApiIssuesIdCommentsRoute
  '/api/issues/$id/events': typeof ApiIssuesIdEventsRoute
  '/api/issues/$id/reactions': typeof ApiIssuesIdReactionsRoute
  '/api/issues/$id/runs': typeof ApiIssuesIdRunsRoute
  '/api/issues/$id/source-bindings': typeof ApiIssuesIdSourceBindingsRouteWithChildren
  '/api/issues/$id/subscribe': typeof ApiIssuesIdSubscribeRoute
  '/api/issues/$id/subscribers': typeof ApiIssuesIdSubscribersRoute
  '/api/issues/$id/timeline': typeof ApiIssuesIdTimelineRoute
  '/api/issues/$id/unsubscribe': typeof ApiIssuesIdUnsubscribeRoute
  '/api/issues/$id/usage': typeof ApiIssuesIdUsageRoute
  '/api/issues/$id/work-products': typeof ApiIssuesIdWorkProductsRoute
  '/api/permission-requests/$id/resolve': typeof ApiPermissionRequestsIdResolveRoute
  '/api/work-products/$id/review': typeof ApiWorkProductsIdReviewRoute
  '/api/workspaces/$id/invitations': typeof ApiWorkspacesIdInvitationsRouteWithChildren
  '/api/workspaces/$id/members': typeof ApiWorkspacesIdMembersRouteWithChildren
  '/api/automations/$id/triggers/$triggerId': typeof ApiAutomationsIdTriggersTriggerIdRoute
  '/api/chat/threads/$id/documents': typeof ApiChatThreadsIdDocumentsRoute
  '/api/chat/threads/$id/primary-issue': typeof ApiChatThreadsIdPrimaryIssueRoute
  '/api/chat/threads/$id/tool-approval': typeof ApiChatThreadsIdToolApprovalRoute
  '/api/issues/$id/source-bindings/$bindingId': typeof ApiIssuesIdSourceBindingsBindingIdRoute
  '/api/workspaces/$id/invitations/$invitationId': typeof ApiWorkspacesIdInvitationsInvitationIdRoute
  '/api/workspaces/$id/members/$memberId': typeof ApiWorkspacesIdMembersMemberIdRoute
  '/api/connections/$connectorId/tools/$name/grant': typeof ApiConnectionsConnectorIdToolsNameGrantRoute
  '/api/documents/$documentId/edits/$editId/$action': typeof ApiDocumentsDocumentIdEditsEditIdActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/automations': typeof ApiAutomationsRouteWithChildren
  '/api/connections': typeof ApiConnectionsRouteWithChildren
  '/api/debug-stream': typeof ApiDebugStreamRoute
  '/api/inbox': typeof ApiInboxRouteWithChildren
  '/api/invitations': typeof ApiInvitationsRouteWithChildren
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/runtimes': typeof ApiRuntimesRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/_authenticated/automations/$id': typeof AuthenticatedAutomationsIdRoute
  '/api/agents/$id': typeof ApiAgentsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/automations/$id': typeof ApiAutomationsIdRouteWithChildren
  '/api/chat/threads': typeof ApiChatThreadsRouteWithChildren
  '/api/comments/$id': typeof ApiCommentsIdRouteWithChildren
  '/api/connections/$connectorId': typeof ApiConnectionsConnectorIdRouteWithChildren
  '/api/dev/issue-run-plan': typeof ApiDevIssueRunPlanRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/inbox/archive-all': typeof ApiInboxArchiveAllRoute
  '/api/inbox/archive-all-read': typeof ApiInboxArchiveAllReadRoute
  '/api/inbox/archive-completed': typeof ApiInboxArchiveCompletedRoute
  '/api/inbox/mark-all-read': typeof ApiInboxMarkAllReadRoute
  '/api/inbox/unread-count': typeof ApiInboxUnreadCountRoute
  '/api/internal/capability-sync': typeof ApiInternalCapabilitySyncRoute
  '/api/invitations/$id': typeof ApiInvitationsIdRouteWithChildren
  '/api/issues/$id': typeof ApiIssuesIdRouteWithChildren
  '/api/issues/child-progress': typeof ApiIssuesChildProgressRoute
  '/api/issues/search': typeof ApiIssuesSearchRoute
  '/api/runs/$id': typeof ApiRunsIdRoute
  '/api/skills/$id': typeof ApiSkillsIdRoute
  '/api/skills/import': typeof ApiSkillsImportRoute
  '/api/skills/preview': typeof ApiSkillsPreviewRoute
  '/api/skills/search': typeof ApiSkillsSearchRoute
  '/api/workspaces/$id': typeof ApiWorkspacesIdRouteWithChildren
  '/_authenticated/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/api/agents/$id/archive': typeof ApiAgentsIdArchiveRoute
  '/api/agents/$id/restore': typeof ApiAgentsIdRestoreRoute
  '/api/agents/$id/skills': typeof ApiAgentsIdSkillsRoute
  '/api/automations/$id/runs': typeof ApiAutomationsIdRunsRoute
  '/api/automations/$id/trigger': typeof ApiAutomationsIdTriggerRoute
  '/api/automations/$id/triggers': typeof ApiAutomationsIdTriggersRouteWithChildren
  '/api/chat/threads/$id': typeof ApiChatThreadsIdRouteWithChildren
  '/api/comments/$id/reactions': typeof ApiCommentsIdReactionsRoute
  '/api/connections/$connectorId/activity': typeof ApiConnectionsConnectorIdActivityRoute
  '/api/documents/$id/display': typeof ApiDocumentsIdDisplayRoute
  '/api/documents/$id/docx': typeof ApiDocumentsIdDocxRoute
  '/api/documents/$id/metadata': typeof ApiDocumentsIdMetadataRoute
  '/api/documents/$id/tracked-change-ids': typeof ApiDocumentsIdTrackedChangeIdsRoute
  '/api/documents/$id/versions': typeof ApiDocumentsIdVersionsRoute
  '/api/inbox/$id/archive': typeof ApiInboxIdArchiveRoute
  '/api/inbox/$id/read': typeof ApiInboxIdReadRoute
  '/api/invitations/$id/accept': typeof ApiInvitationsIdAcceptRoute
  '/api/invitations/$id/decline': typeof ApiInvitationsIdDeclineRoute
  '/api/issues/$id/active-run': typeof ApiIssuesIdActiveRunRoute
  '/api/issues/$id/cancel': typeof ApiIssuesIdCancelRoute
  '/api/issues/$id/comments': typeof ApiIssuesIdCommentsRoute
  '/api/issues/$id/events': typeof ApiIssuesIdEventsRoute
  '/api/issues/$id/reactions': typeof ApiIssuesIdReactionsRoute
  '/api/issues/$id/runs': typeof ApiIssuesIdRunsRoute
  '/api/issues/$id/source-bindings': typeof ApiIssuesIdSourceBindingsRouteWithChildren
  '/api/issues/$id/subscribe': typeof ApiIssuesIdSubscribeRoute
  '/api/issues/$id/subscribers': typeof ApiIssuesIdSubscribersRoute
  '/api/issues/$id/timeline': typeof ApiIssuesIdTimelineRoute
  '/api/issues/$id/unsubscribe': typeof ApiIssuesIdUnsubscribeRoute
  '/api/issues/$id/usage': typeof ApiIssuesIdUsageRoute
  '/api/issues/$id/work-products': typeof ApiIssuesIdWorkProductsRoute
  '/api/permission-requests/$id/resolve': typeof ApiPermissionRequestsIdResolveRoute
  '/api/work-products/$id/review': typeof ApiWorkProductsIdReviewRoute
  '/api/workspaces/$id/invitations': typeof ApiWorkspacesIdInvitationsRouteWithChildren
  '/api/workspaces/$id/members': typeof ApiWorkspacesIdMembersRouteWithChildren
  '/api/automations/$id/triggers/$triggerId': typeof ApiAutomationsIdTriggersTriggerIdRoute
  '/api/chat/threads/$id/documents': typeof ApiChatThreadsIdDocumentsRoute
  '/api/chat/threads/$id/primary-issue': typeof ApiChatThreadsIdPrimaryIssueRoute
  '/api/chat/threads/$id/tool-approval': typeof ApiChatThreadsIdToolApprovalRoute
  '/api/issues/$id/source-bindings/$bindingId': typeof ApiIssuesIdSourceBindingsBindingIdRoute
  '/api/workspaces/$id/invitations/$invitationId': typeof ApiWorkspacesIdInvitationsInvitationIdRoute
  '/api/workspaces/$id/members/$memberId': typeof ApiWorkspacesIdMembersMemberIdRoute
  '/api/connections/$connectorId/tools/$name/grant': typeof ApiConnectionsConnectorIdToolsNameGrantRoute
  '/api/documents/$documentId/edits/$editId/$action': typeof ApiDocumentsDocumentIdEditsEditIdActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/api/agents'
    | '/api/automations'
    | '/api/connections'
    | '/api/debug-stream'
    | '/api/inbox'
    | '/api/invitations'
    | '/api/issues'
    | '/api/me'
    | '/api/projects'
    | '/api/runtimes'
    | '/api/skills'
    | '/api/workspaces'
    | '/automations/$id'
    | '/api/agents/$id'
    | '/api/auth/$'
    | '/api/automations/$id'
    | '/api/chat/threads'
    | '/api/comments/$id'
    | '/api/connections/$connectorId'
    | '/api/dev/issue-run-plan'
    | '/api/github/callback'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/inbox/archive-all'
    | '/api/inbox/archive-all-read'
    | '/api/inbox/archive-completed'
    | '/api/inbox/mark-all-read'
    | '/api/inbox/unread-count'
    | '/api/internal/capability-sync'
    | '/api/invitations/$id'
    | '/api/issues/$id'
    | '/api/issues/child-progress'
    | '/api/issues/search'
    | '/api/runs/$id'
    | '/api/skills/$id'
    | '/api/skills/import'
    | '/api/skills/preview'
    | '/api/skills/search'
    | '/api/workspaces/$id'
    | '/automations/'
    | '/api/agents/$id/archive'
    | '/api/agents/$id/restore'
    | '/api/agents/$id/skills'
    | '/api/automations/$id/runs'
    | '/api/automations/$id/trigger'
    | '/api/automations/$id/triggers'
    | '/api/chat/threads/$id'
    | '/api/comments/$id/reactions'
    | '/api/connections/$connectorId/activity'
    | '/api/documents/$id/display'
    | '/api/documents/$id/docx'
    | '/api/documents/$id/metadata'
    | '/api/documents/$id/tracked-change-ids'
    | '/api/documents/$id/versions'
    | '/api/inbox/$id/archive'
    | '/api/inbox/$id/read'
    | '/api/invitations/$id/accept'
    | '/api/invitations/$id/decline'
    | '/api/issues/$id/active-run'
    | '/api/issues/$id/cancel'
    | '/api/issues/$id/comments'
    | '/api/issues/$id/events'
    | '/api/issues/$id/reactions'
    | '/api/issues/$id/runs'
    | '/api/issues/$id/source-bindings'
    | '/api/issues/$id/subscribe'
    | '/api/issues/$id/subscribers'
    | '/api/issues/$id/timeline'
    | '/api/issues/$id/unsubscribe'
    | '/api/issues/$id/usage'
    | '/api/issues/$id/work-products'
    | '/api/permission-requests/$id/resolve'
    | '/api/work-products/$id/review'
    | '/api/workspaces/$id/invitations'
    | '/api/workspaces/$id/members'
    | '/api/automations/$id/triggers/$triggerId'
    | '/api/chat/threads/$id/documents'
    | '/api/chat/threads/$id/primary-issue'
    | '/api/chat/threads/$id/tool-approval'
    | '/api/issues/$id/source-bindings/$bindingId'
    | '/api/workspaces/$id/invitations/$invitationId'
    | '/api/workspaces/$id/members/$memberId'
    | '/api/connections/$connectorId/tools/$name/grant'
    | '/api/documents/$documentId/edits/$editId/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/api/agents'
    | '/api/automations'
    | '/api/connections'
    | '/api/debug-stream'
    | '/api/inbox'
    | '/api/invitations'
    | '/api/issues'
    | '/api/me'
    | '/api/projects'
    | '/api/runtimes'
    | '/api/skills'
    | '/api/workspaces'
    | '/automations/$id'
    | '/api/agents/$id'
    | '/api/auth/$'
    | '/api/automations/$id'
    | '/api/chat/threads'
    | '/api/comments/$id'
    | '/api/connections/$connectorId'
    | '/api/dev/issue-run-plan'
    | '/api/github/callback'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/inbox/archive-all'
    | '/api/inbox/archive-all-read'
    | '/api/inbox/archive-completed'
    | '/api/inbox/mark-all-read'
    | '/api/inbox/unread-count'
    | '/api/internal/capability-sync'
    | '/api/invitations/$id'
    | '/api/issues/$id'
    | '/api/issues/child-progress'
    | '/api/issues/search'
    | '/api/runs/$id'
    | '/api/skills/$id'
    | '/api/skills/import'
    | '/api/skills/preview'
    | '/api/skills/search'
    | '/api/workspaces/$id'
    | '/automations'
    | '/api/agents/$id/archive'
    | '/api/agents/$id/restore'
    | '/api/agents/$id/skills'
    | '/api/automations/$id/runs'
    | '/api/automations/$id/trigger'
    | '/api/automations/$id/triggers'
    | '/api/chat/threads/$id'
    | '/api/comments/$id/reactions'
    | '/api/connections/$connectorId/activity'
    | '/api/documents/$id/display'
    | '/api/documents/$id/docx'
    | '/api/documents/$id/metadata'
    | '/api/documents/$id/tracked-change-ids'
    | '/api/documents/$id/versions'
    | '/api/inbox/$id/archive'
    | '/api/inbox/$id/read'
    | '/api/invitations/$id/accept'
    | '/api/invitations/$id/decline'
    | '/api/issues/$id/active-run'
    | '/api/issues/$id/cancel'
    | '/api/issues/$id/comments'
    | '/api/issues/$id/events'
    | '/api/issues/$id/reactions'
    | '/api/issues/$id/runs'
    | '/api/issues/$id/source-bindings'
    | '/api/issues/$id/subscribe'
    | '/api/issues/$id/subscribers'
    | '/api/issues/$id/timeline'
    | '/api/issues/$id/unsubscribe'
    | '/api/issues/$id/usage'
    | '/api/issues/$id/work-products'
    | '/api/permission-requests/$id/resolve'
    | '/api/work-products/$id/review'
    | '/api/workspaces/$id/invitations'
    | '/api/workspaces/$id/members'
    | '/api/automations/$id/triggers/$triggerId'
    | '/api/chat/threads/$id/documents'
    | '/api/chat/threads/$id/primary-issue'
    | '/api/chat/threads/$id/tool-approval'
    | '/api/issues/$id/source-bindings/$bindingId'
    | '/api/workspaces/$id/invitations/$invitationId'
    | '/api/workspaces/$id/members/$memberId'
    | '/api/connections/$connectorId/tools/$name/grant'
    | '/api/documents/$documentId/edits/$editId/$action'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/workspace'
    | '/api/agents'
    | '/api/automations'
    | '/api/connections'
    | '/api/debug-stream'
    | '/api/inbox'
    | '/api/invitations'
    | '/api/issues'
    | '/api/me'
    | '/api/projects'
    | '/api/runtimes'
    | '/api/skills'
    | '/api/workspaces'
    | '/_authenticated/automations/$id'
    | '/api/agents/$id'
    | '/api/auth/$'
    | '/api/automations/$id'
    | '/api/chat/threads'
    | '/api/comments/$id'
    | '/api/connections/$connectorId'
    | '/api/dev/issue-run-plan'
    | '/api/github/callback'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/inbox/archive-all'
    | '/api/inbox/archive-all-read'
    | '/api/inbox/archive-completed'
    | '/api/inbox/mark-all-read'
    | '/api/inbox/unread-count'
    | '/api/internal/capability-sync'
    | '/api/invitations/$id'
    | '/api/issues/$id'
    | '/api/issues/child-progress'
    | '/api/issues/search'
    | '/api/runs/$id'
    | '/api/skills/$id'
    | '/api/skills/import'
    | '/api/skills/preview'
    | '/api/skills/search'
    | '/api/workspaces/$id'
    | '/_authenticated/automations/'
    | '/api/agents/$id/archive'
    | '/api/agents/$id/restore'
    | '/api/agents/$id/skills'
    | '/api/automations/$id/runs'
    | '/api/automations/$id/trigger'
    | '/api/automations/$id/triggers'
    | '/api/chat/threads/$id'
    | '/api/comments/$id/reactions'
    | '/api/connections/$connectorId/activity'
    | '/api/documents/$id/display'
    | '/api/documents/$id/docx'
    | '/api/documents/$id/metadata'
    | '/api/documents/$id/tracked-change-ids'
    | '/api/documents/$id/versions'
    | '/api/inbox/$id/archive'
    | '/api/inbox/$id/read'
    | '/api/invitations/$id/accept'
    | '/api/invitations/$id/decline'
    | '/api/issues/$id/active-run'
    | '/api/issues/$id/cancel'
    | '/api/issues/$id/comments'
    | '/api/issues/$id/events'
    | '/api/issues/$id/reactions'
    | '/api/issues/$id/runs'
    | '/api/issues/$id/source-bindings'
    | '/api/issues/$id/subscribe'
    | '/api/issues/$id/subscribers'
    | '/api/issues/$id/timeline'
    | '/api/issues/$id/unsubscribe'
    | '/api/issues/$id/usage'
    | '/api/issues/$id/work-products'
    | '/api/permission-requests/$id/resolve'
    | '/api/work-products/$id/review'
    | '/api/workspaces/$id/invitations'
    | '/api/workspaces/$id/members'
    | '/api/automations/$id/triggers/$triggerId'
    | '/api/chat/threads/$id/documents'
    | '/api/chat/threads/$id/primary-issue'
    | '/api/chat/threads/$id/tool-approval'
    | '/api/issues/$id/source-bindings/$bindingId'
    | '/api/workspaces/$id/invitations/$invitationId'
    | '/api/workspaces/$id/members/$memberId'
    | '/api/connections/$connectorId/tools/$name/grant'
    | '/api/documents/$documentId/edits/$editId/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAgentsRoute: typeof ApiAgentsRouteWithChildren
  ApiAutomationsRoute: typeof ApiAutomationsRouteWithChildren
  ApiConnectionsRoute: typeof ApiConnectionsRouteWithChildren
  ApiDebugStreamRoute: typeof ApiDebugStreamRoute
  ApiInboxRoute: typeof ApiInboxRouteWithChildren
  ApiInvitationsRoute: typeof ApiInvitationsRouteWithChildren
  ApiIssuesRoute: typeof ApiIssuesRouteWithChildren
  ApiMeRoute: typeof ApiMeRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiRuntimesRoute: typeof ApiRuntimesRoute
  ApiSkillsRoute: typeof ApiSkillsRouteWithChildren
  ApiWorkspacesRoute: typeof ApiWorkspacesRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatThreadsRoute: typeof ApiChatThreadsRouteWithChildren
  ApiCommentsIdRoute: typeof ApiCommentsIdRouteWithChildren
  ApiDevIssueRunPlanRoute: typeof ApiDevIssueRunPlanRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubInstallRoute: typeof ApiGithubInstallRoute
  ApiGithubSetupRoute: typeof ApiGithubSetupRoute
  ApiInternalCapabilitySyncRoute: typeof ApiInternalCapabilitySyncRoute
  ApiRunsIdRoute: typeof ApiRunsIdRoute
  ApiDocumentsIdDisplayRoute: typeof ApiDocumentsIdDisplayRoute
  ApiDocumentsIdDocxRoute: typeof ApiDocumentsIdDocxRoute
  ApiDocumentsIdMetadataRoute: typeof ApiDocumentsIdMetadataRoute
  ApiDocumentsIdTrackedChangeIdsRoute: typeof ApiDocumentsIdTrackedChangeIdsRoute
  ApiDocumentsIdVersionsRoute: typeof ApiDocumentsIdVersionsRoute
  ApiPermissionRequestsIdResolveRoute: typeof ApiPermissionRequestsIdResolveRoute
  ApiWorkProductsIdReviewRoute: typeof ApiWorkProductsIdReviewRoute
  ApiDocumentsDocumentIdEditsEditIdActionRoute: typeof ApiDocumentsDocumentIdEditsEditIdActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces': {
      id: '/api/workspaces'
      path: '/api/workspaces'
      fullPath: '/api/workspaces'
      preLoaderRoute: typeof ApiWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtimes': {
      id: '/api/runtimes'
      path: '/api/runtimes'
      fullPath: '/api/runtimes'
      preLoaderRoute: typeof ApiRuntimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/issues': {
      id: '/api/issues'
      path: '/api/issues'
      fullPath: '/api/issues'
      preLoaderRoute: typeof ApiIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations': {
      id: '/api/invitations'
      path: '/api/invitations'
      fullPath: '/api/invitations'
      preLoaderRoute: typeof ApiInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-stream': {
      id: '/api/debug-stream'
      path: '/api/debug-stream'
      fullPath: '/api/debug-stream'
      preLoaderRoute: typeof ApiDebugStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections': {
      id: '/api/connections'
      path: '/api/connections'
      fullPath: '/api/connections'
      preLoaderRoute: typeof ApiConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automations': {
      id: '/api/automations'
      path: '/api/automations'
      fullPath: '/api/automations'
      preLoaderRoute: typeof ApiAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automations/': {
      id: '/_authenticated/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AuthenticatedAutomationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/workspaces/$id': {
      id: '/api/workspaces/$id'
      path: '/$id'
      fullPath: '/api/workspaces/$id'
      preLoaderRoute: typeof ApiWorkspacesIdRouteImport
      parentRoute: typeof ApiWorkspacesRoute
    }
    '/api/skills/search': {
      id: '/api/skills/search'
      path: '/search'
      fullPath: '/api/skills/search'
      preLoaderRoute: typeof ApiSkillsSearchRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/preview': {
      id: '/api/skills/preview'
      path: '/preview'
      fullPath: '/api/skills/preview'
      preLoaderRoute: typeof ApiSkillsPreviewRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/import': {
      id: '/api/skills/import'
      path: '/import'
      fullPath: '/api/skills/import'
      preLoaderRoute: typeof ApiSkillsImportRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/$id': {
      id: '/api/skills/$id'
      path: '/$id'
      fullPath: '/api/skills/$id'
      preLoaderRoute: typeof ApiSkillsIdRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/runs/$id': {
      id: '/api/runs/$id'
      path: '/api/runs/$id'
      fullPath: '/api/runs/$id'
      preLoaderRoute: typeof ApiRunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/issues/search': {
      id: '/api/issues/search'
      path: '/search'
      fullPath: '/api/issues/search'
      preLoaderRoute: typeof ApiIssuesSearchRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/issues/child-progress': {
      id: '/api/issues/child-progress'
      path: '/child-progress'
      fullPath: '/api/issues/child-progress'
      preLoaderRoute: typeof ApiIssuesChildProgressRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/issues/$id': {
      id: '/api/issues/$id'
      path: '/$id'
      fullPath: '/api/issues/$id'
      preLoaderRoute: typeof ApiIssuesIdRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/invitations/$id': {
      id: '/api/invitations/$id'
      path: '/$id'
      fullPath: '/api/invitations/$id'
      preLoaderRoute: typeof ApiInvitationsIdRouteImport
      parentRoute: typeof ApiInvitationsRoute
    }
    '/api/internal/capability-sync': {
      id: '/api/internal/capability-sync'
      path: '/api/internal/capability-sync'
      fullPath: '/api/internal/capability-sync'
      preLoaderRoute: typeof ApiInternalCapabilitySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox/unread-count': {
      id: '/api/inbox/unread-count'
      path: '/unread-count'
      fullPath: '/api/inbox/unread-count'
      preLoaderRoute: typeof ApiInboxUnreadCountRouteImport
      parentRoute: typeof ApiInboxRoute
    }
    '/api/inbox/mark-all-read': {
      id: '/api/inbox/mark-all-read'
      path: '/mark-all-read'
      fullPath: '/api/inbox/mark-all-read'
      preLoaderRoute: typeof ApiInboxMarkAllReadRouteImport
      parentRoute: typeof ApiInboxRoute
    }
    '/api/inbox/archive-completed': {
      id: '/api/inbox/archive-completed'
      path: '/archive-completed'
      fullPath: '/api/inbox/archive-completed'
      preLoaderRoute: typeof ApiInboxArchiveCompletedRouteImport
      parentRoute: typeof ApiInboxRoute
    }
    '/api/inbox/archive-all-read': {
      id: '/api/inbox/archive-all-read'
      path: '/archive-all-read'
      fullPath: '/api/inbox/archive-all-read'
      preLoaderRoute: typeof ApiInboxArchiveAllReadRouteImport
      parentRoute: typeof ApiInboxRoute
    }
    '/api/inbox/archive-all': {
      id: '/api/inbox/archive-all'
      path: '/archive-all'
      fullPath: '/api/inbox/archive-all'
      preLoaderRoute: typeof ApiInboxArchiveAllRouteImport
      parentRoute: typeof ApiInboxRoute
    }
    '/api/github/setup': {
      id: '/api/github/setup'
      path: '/api/github/setup'
      fullPath: '/api/github/setup'
      preLoaderRoute: typeof ApiGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install': {
      id: '/api/github/install'
      path: '/api/github/install'
      fullPath: '/api/github/install'
      preLoaderRoute: typeof ApiGithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/issue-run-plan': {
      id: '/api/dev/issue-run-plan'
      path: '/api/dev/issue-run-plan'
      fullPath: '/api/dev/issue-run-plan'
      preLoaderRoute: typeof ApiDevIssueRunPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections/$connectorId': {
      id: '/api/connections/$connectorId'
      path: '/$connectorId'
      fullPath: '/api/connections/$connectorId'
      preLoaderRoute: typeof ApiConnectionsConnectorIdRouteImport
      parentRoute: typeof ApiConnectionsRoute
    }
    '/api/comments/$id': {
      id: '/api/comments/$id'
      path: '/api/comments/$id'
      fullPath: '/api/comments/$id'
      preLoaderRoute: typeof ApiCommentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/threads': {
      id: '/api/chat/threads'
      path: '/api/chat/threads'
      fullPath: '/api/chat/threads'
      preLoaderRoute: typeof ApiChatThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automations/$id': {
      id: '/api/automations/$id'
      path: '/$id'
      fullPath: '/api/automations/$id'
      preLoaderRoute: typeof ApiAutomationsIdRouteImport
      parentRoute: typeof ApiAutomationsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$id': {
      id: '/api/agents/$id'
      path: '/$id'
      fullPath: '/api/agents/$id'
      preLoaderRoute: typeof ApiAgentsIdRouteImport
      parentRoute: typeof ApiAgentsRoute
    }
    '/_authenticated/automations/$id': {
      id: '/_authenticated/automations/$id'
      path: '/automations/$id'
      fullPath: '/automations/$id'
      preLoaderRoute: typeof AuthenticatedAutomationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/workspaces/$id/members': {
      id: '/api/workspaces/$id/members'
      path: '/members'
      fullPath: '/api/workspaces/$id/members'
      preLoaderRoute: typeof ApiWorkspacesIdMembersRouteImport
      parentRoute: typeof ApiWorkspacesIdRoute
    }
    '/api/workspaces/$id/invitations': {
      id: '/api/workspaces/$id/invitations'
      path: '/invitations'
      fullPath: '/api/workspaces/$id/invitations'
      preLoaderRoute: typeof ApiWorkspacesIdInvitationsRouteImport
      parentRoute: typeof ApiWorkspacesIdRoute
    }
    '/api/work-products/$id/review': {
      id: '/api/work-products/$id/review'
      path: '/api/work-products/$id/review'
      fullPath: '/api/work-products/$id/review'
      preLoaderRoute: typeof ApiWorkProductsIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/permission-requests/$id/resolve': {
      id: '/api/permission-requests/$id/resolve'
      path: '/api/permission-requests/$id/resolve'
      fullPath: '/api/permission-requests/$id/resolve'
      preLoaderRoute: typeof ApiPermissionRequestsIdResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/issues/$id/work-products': {
      id: '/api/issues/$id/work-products'
      path: '/work-products'
      fullPath: '/api/issues/$id/work-products'
      preLoaderRoute: typeof ApiIssuesIdWorkProductsRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/usage': {
      id: '/api/issues/$id/usage'
      path: '/usage'
      fullPath: '/api/issues/$id/usage'
      preLoaderRoute: typeof ApiIssuesIdUsageRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/unsubscribe': {
      id: '/api/issues/$id/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/api/issues/$id/unsubscribe'
      preLoaderRoute: typeof ApiIssuesIdUnsubscribeRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/timeline': {
      id: '/api/issues/$id/timeline'
      path: '/timeline'
      fullPath: '/api/issues/$id/timeline'
      preLoaderRoute: typeof ApiIssuesIdTimelineRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/subscribers': {
      id: '/api/issues/$id/subscribers'
      path: '/subscribers'
      fullPath: '/api/issues/$id/subscribers'
      preLoaderRoute: typeof ApiIssuesIdSubscribersRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/subscribe': {
      id: '/api/issues/$id/subscribe'
      path: '/subscribe'
      fullPath: '/api/issues/$id/subscribe'
      preLoaderRoute: typeof ApiIssuesIdSubscribeRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/source-bindings': {
      id: '/api/issues/$id/source-bindings'
      path: '/source-bindings'
      fullPath: '/api/issues/$id/source-bindings'
      preLoaderRoute: typeof ApiIssuesIdSourceBindingsRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/runs': {
      id: '/api/issues/$id/runs'
      path: '/runs'
      fullPath: '/api/issues/$id/runs'
      preLoaderRoute: typeof ApiIssuesIdRunsRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/reactions': {
      id: '/api/issues/$id/reactions'
      path: '/reactions'
      fullPath: '/api/issues/$id/reactions'
      preLoaderRoute: typeof ApiIssuesIdReactionsRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/events': {
      id: '/api/issues/$id/events'
      path: '/events'
      fullPath: '/api/issues/$id/events'
      preLoaderRoute: typeof ApiIssuesIdEventsRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/comments': {
      id: '/api/issues/$id/comments'
      path: '/comments'
      fullPath: '/api/issues/$id/comments'
      preLoaderRoute: typeof ApiIssuesIdCommentsRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/cancel': {
      id: '/api/issues/$id/cancel'
      path: '/cancel'
      fullPath: '/api/issues/$id/cancel'
      preLoaderRoute: typeof ApiIssuesIdCancelRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/active-run': {
      id: '/api/issues/$id/active-run'
      path: '/active-run'
      fullPath: '/api/issues/$id/active-run'
      preLoaderRoute: typeof ApiIssuesIdActiveRunRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/invitations/$id/decline': {
      id: '/api/invitations/$id/decline'
      path: '/decline'
      fullPath: '/api/invitations/$id/decline'
      preLoaderRoute: typeof ApiInvitationsIdDeclineRouteImport
      parentRoute: typeof ApiInvitationsIdRoute
    }
    '/api/invitations/$id/accept': {
      id: '/api/invitations/$id/accept'
      path: '/accept'
      fullPath: '/api/invitations/$id/accept'
      preLoaderRoute: typeof ApiInvitationsIdAcceptRouteImport
      parentRoute: typeof ApiInvitationsIdRoute
    }
    '/api/inbox/$id/read': {
      id: '/api/inbox/$id/read'
      path: '/$id/read'
      fullPath: '/api/inbox/$id/read'
      preLoaderRoute: typeof ApiInboxIdReadRouteImport
      parentRoute: typeof ApiInboxRoute
    }
    '/api/inbox/$id/archive': {
      id: '/api/inbox/$id/archive'
      path: '/$id/archive'
      fullPath: '/api/inbox/$id/archive'
      preLoaderRoute: typeof ApiInboxIdArchiveRouteImport
      parentRoute: typeof ApiInboxRoute
    }
    '/api/documents/$id/versions': {
      id: '/api/documents/$id/versions'
      path: '/api/documents/$id/versions'
      fullPath: '/api/documents/$id/versions'
      preLoaderRoute: typeof ApiDocumentsIdVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$id/tracked-change-ids': {
      id: '/api/documents/$id/tracked-change-ids'
      path: '/api/documents/$id/tracked-change-ids'
      fullPath: '/api/documents/$id/tracked-change-ids'
      preLoaderRoute: typeof ApiDocumentsIdTrackedChangeIdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$id/metadata': {
      id: '/api/documents/$id/metadata'
      path: '/api/documents/$id/metadata'
      fullPath: '/api/documents/$id/metadata'
      preLoaderRoute: typeof ApiDocumentsIdMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$id/docx': {
      id: '/api/documents/$id/docx'
      path: '/api/documents/$id/docx'
      fullPath: '/api/documents/$id/docx'
      preLoaderRoute: typeof ApiDocumentsIdDocxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$id/display': {
      id: '/api/documents/$id/display'
      path: '/api/documents/$id/display'
      fullPath: '/api/documents/$id/display'
      preLoaderRoute: typeof ApiDocumentsIdDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections/$connectorId/activity': {
      id: '/api/connections/$connectorId/activity'
      path: '/activity'
      fullPath: '/api/connections/$connectorId/activity'
      preLoaderRoute: typeof ApiConnectionsConnectorIdActivityRouteImport
      parentRoute: typeof ApiConnectionsConnectorIdRoute
    }
    '/api/comments/$id/reactions': {
      id: '/api/comments/$id/reactions'
      path: '/reactions'
      fullPath: '/api/comments/$id/reactions'
      preLoaderRoute: typeof ApiCommentsIdReactionsRouteImport
      parentRoute: typeof ApiCommentsIdRoute
    }
    '/api/chat/threads/$id': {
      id: '/api/chat/threads/$id'
      path: '/$id'
      fullPath: '/api/chat/threads/$id'
      preLoaderRoute: typeof ApiChatThreadsIdRouteImport
      parentRoute: typeof ApiChatThreadsRoute
    }
    '/api/automations/$id/triggers': {
      id: '/api/automations/$id/triggers'
      path: '/triggers'
      fullPath: '/api/automations/$id/triggers'
      preLoaderRoute: typeof ApiAutomationsIdTriggersRouteImport
      parentRoute: typeof ApiAutomationsIdRoute
    }
    '/api/automations/$id/trigger': {
      id: '/api/automations/$id/trigger'
      path: '/trigger'
      fullPath: '/api/automations/$id/trigger'
      preLoaderRoute: typeof ApiAutomationsIdTriggerRouteImport
      parentRoute: typeof ApiAutomationsIdRoute
    }
    '/api/automations/$id/runs': {
      id: '/api/automations/$id/runs'
      path: '/runs'
      fullPath: '/api/automations/$id/runs'
      preLoaderRoute: typeof ApiAutomationsIdRunsRouteImport
      parentRoute: typeof ApiAutomationsIdRoute
    }
    '/api/agents/$id/skills': {
      id: '/api/agents/$id/skills'
      path: '/skills'
      fullPath: '/api/agents/$id/skills'
      preLoaderRoute: typeof ApiAgentsIdSkillsRouteImport
      parentRoute: typeof ApiAgentsIdRoute
    }
    '/api/agents/$id/restore': {
      id: '/api/agents/$id/restore'
      path: '/restore'
      fullPath: '/api/agents/$id/restore'
      preLoaderRoute: typeof ApiAgentsIdRestoreRouteImport
      parentRoute: typeof ApiAgentsIdRoute
    }
    '/api/agents/$id/archive': {
      id: '/api/agents/$id/archive'
      path: '/archive'
      fullPath: '/api/agents/$id/archive'
      preLoaderRoute: typeof ApiAgentsIdArchiveRouteImport
      parentRoute: typeof ApiAgentsIdRoute
    }
    '/api/workspaces/$id/members/$memberId': {
      id: '/api/workspaces/$id/members/$memberId'
      path: '/$memberId'
      fullPath: '/api/workspaces/$id/members/$memberId'
      preLoaderRoute: typeof ApiWorkspacesIdMembersMemberIdRouteImport
      parentRoute: typeof ApiWorkspacesIdMembersRoute
    }
    '/api/workspaces/$id/invitations/$invitationId': {
      id: '/api/workspaces/$id/invitations/$invitationId'
      path: '/$invitationId'
      fullPath: '/api/workspaces/$id/invitations/$invitationId'
      preLoaderRoute: typeof ApiWorkspacesIdInvitationsInvitationIdRouteImport
      parentRoute: typeof ApiWorkspacesIdInvitationsRoute
    }
    '/api/issues/$id/source-bindings/$bindingId': {
      id: '/api/issues/$id/source-bindings/$bindingId'
      path: '/$bindingId'
      fullPath: '/api/issues/$id/source-bindings/$bindingId'
      preLoaderRoute: typeof ApiIssuesIdSourceBindingsBindingIdRouteImport
      parentRoute: typeof ApiIssuesIdSourceBindingsRoute
    }
    '/api/chat/threads/$id/tool-approval': {
      id: '/api/chat/threads/$id/tool-approval'
      path: '/tool-approval'
      fullPath: '/api/chat/threads/$id/tool-approval'
      preLoaderRoute: typeof ApiChatThreadsIdToolApprovalRouteImport
      parentRoute: typeof ApiChatThreadsIdRoute
    }
    '/api/chat/threads/$id/primary-issue': {
      id: '/api/chat/threads/$id/primary-issue'
      path: '/primary-issue'
      fullPath: '/api/chat/threads/$id/primary-issue'
      preLoaderRoute: typeof ApiChatThreadsIdPrimaryIssueRouteImport
      parentRoute: typeof ApiChatThreadsIdRoute
    }
    '/api/chat/threads/$id/documents': {
      id: '/api/chat/threads/$id/documents'
      path: '/documents'
      fullPath: '/api/chat/threads/$id/documents'
      preLoaderRoute: typeof ApiChatThreadsIdDocumentsRouteImport
      parentRoute: typeof ApiChatThreadsIdRoute
    }
    '/api/automations/$id/triggers/$triggerId': {
      id: '/api/automations/$id/triggers/$triggerId'
      path: '/$triggerId'
      fullPath: '/api/automations/$id/triggers/$triggerId'
      preLoaderRoute: typeof ApiAutomationsIdTriggersTriggerIdRouteImport
      parentRoute: typeof ApiAutomationsIdTriggersRoute
    }
    '/api/documents/$documentId/edits/$editId/$action': {
      id: '/api/documents/$documentId/edits/$editId/$action'
      path: '/api/documents/$documentId/edits/$editId/$action'
      fullPath: '/api/documents/$documentId/edits/$editId/$action'
      preLoaderRoute: typeof ApiDocumentsDocumentIdEditsEditIdActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections/$connectorId/tools/$name/grant': {
      id: '/api/connections/$connectorId/tools/$name/grant'
      path: '/tools/$name/grant'
      fullPath: '/api/connections/$connectorId/tools/$name/grant'
      preLoaderRoute: typeof ApiConnectionsConnectorIdToolsNameGrantRouteImport
      parentRoute: typeof ApiConnectionsConnectorIdRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedAutomationsIdRoute: typeof AuthenticatedAutomationsIdRoute
  AuthenticatedAutomationsIndexRoute: typeof AuthenticatedAutomationsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedAutomationsIdRoute: AuthenticatedAutomationsIdRoute,
  AuthenticatedAutomationsIndexRoute: AuthenticatedAutomationsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiAgentsIdRouteChildren {
  ApiAgentsIdArchiveRoute: typeof ApiAgentsIdArchiveRoute
  ApiAgentsIdRestoreRoute: typeof ApiAgentsIdRestoreRoute
  ApiAgentsIdSkillsRoute: typeof ApiAgentsIdSkillsRoute
}

const ApiAgentsIdRouteChildren: ApiAgentsIdRouteChildren = {
  ApiAgentsIdArchiveRoute: ApiAgentsIdArchiveRoute,
  ApiAgentsIdRestoreRoute: ApiAgentsIdRestoreRoute,
  ApiAgentsIdSkillsRoute: ApiAgentsIdSkillsRoute,
}

const ApiAgentsIdRouteWithChildren = ApiAgentsIdRoute._addFileChildren(
  ApiAgentsIdRouteChildren,
)

interface ApiAgentsRouteChildren {
  ApiAgentsIdRoute: typeof ApiAgentsIdRouteWithChildren
}

const ApiAgentsRouteChildren: ApiAgentsRouteChildren = {
  ApiAgentsIdRoute: ApiAgentsIdRouteWithChildren,
}

const ApiAgentsRouteWithChildren = ApiAgentsRoute._addFileChildren(
  ApiAgentsRouteChildren,
)

interface ApiAutomationsIdTriggersRouteChildren {
  ApiAutomationsIdTriggersTriggerIdRoute: typeof ApiAutomationsIdTriggersTriggerIdRoute
}

const ApiAutomationsIdTriggersRouteChildren: ApiAutomationsIdTriggersRouteChildren =
  {
    ApiAutomationsIdTriggersTriggerIdRoute:
      ApiAutomationsIdTriggersTriggerIdRoute,
  }

const ApiAutomationsIdTriggersRouteWithChildren =
  ApiAutomationsIdTriggersRoute._addFileChildren(
    ApiAutomationsIdTriggersRouteChildren,
  )

interface ApiAutomationsIdRouteChildren {
  ApiAutomationsIdRunsRoute: typeof ApiAutomationsIdRunsRoute
  ApiAutomationsIdTriggerRoute: typeof ApiAutomationsIdTriggerRoute
  ApiAutomationsIdTriggersRoute: typeof ApiAutomationsIdTriggersRouteWithChildren
}

const ApiAutomationsIdRouteChildren: ApiAutomationsIdRouteChildren = {
  ApiAutomationsIdRunsRoute: ApiAutomationsIdRunsRoute,
  ApiAutomationsIdTriggerRoute: ApiAutomationsIdTriggerRoute,
  ApiAutomationsIdTriggersRoute: ApiAutomationsIdTriggersRouteWithChildren,
}

const ApiAutomationsIdRouteWithChildren =
  ApiAutomationsIdRoute._addFileChildren(ApiAutomationsIdRouteChildren)

interface ApiAutomationsRouteChildren {
  ApiAutomationsIdRoute: typeof ApiAutomationsIdRouteWithChildren
}

const ApiAutomationsRouteChildren: ApiAutomationsRouteChildren = {
  ApiAutomationsIdRoute: ApiAutomationsIdRouteWithChildren,
}

const ApiAutomationsRouteWithChildren = ApiAutomationsRoute._addFileChildren(
  ApiAutomationsRouteChildren,
)

interface ApiConnectionsConnectorIdRouteChildren {
  ApiConnectionsConnectorIdActivityRoute: typeof ApiConnectionsConnectorIdActivityRoute
  ApiConnectionsConnectorIdToolsNameGrantRoute: typeof ApiConnectionsConnectorIdToolsNameGrantRoute
}

const ApiConnectionsConnectorIdRouteChildren: ApiConnectionsConnectorIdRouteChildren =
  {
    ApiConnectionsConnectorIdActivityRoute:
      ApiConnectionsConnectorIdActivityRoute,
    ApiConnectionsConnectorIdToolsNameGrantRoute:
      ApiConnectionsConnectorIdToolsNameGrantRoute,
  }

const ApiConnectionsConnectorIdRouteWithChildren =
  ApiConnectionsConnectorIdRoute._addFileChildren(
    ApiConnectionsConnectorIdRouteChildren,
  )

interface ApiConnectionsRouteChildren {
  ApiConnectionsConnectorIdRoute: typeof ApiConnectionsConnectorIdRouteWithChildren
}

const ApiConnectionsRouteChildren: ApiConnectionsRouteChildren = {
  ApiConnectionsConnectorIdRoute: ApiConnectionsConnectorIdRouteWithChildren,
}

const ApiConnectionsRouteWithChildren = ApiConnectionsRoute._addFileChildren(
  ApiConnectionsRouteChildren,
)

interface ApiInboxRouteChildren {
  ApiInboxArchiveAllRoute: typeof ApiInboxArchiveAllRoute
  ApiInboxArchiveAllReadRoute: typeof ApiInboxArchiveAllReadRoute
  ApiInboxArchiveCompletedRoute: typeof ApiInboxArchiveCompletedRoute
  ApiInboxMarkAllReadRoute: typeof ApiInboxMarkAllReadRoute
  ApiInboxUnreadCountRoute: typeof ApiInboxUnreadCountRoute
  ApiInboxIdArchiveRoute: typeof ApiInboxIdArchiveRoute
  ApiInboxIdReadRoute: typeof ApiInboxIdReadRoute
}

const ApiInboxRouteChildren: ApiInboxRouteChildren = {
  ApiInboxArchiveAllRoute: ApiInboxArchiveAllRoute,
  ApiInboxArchiveAllReadRoute: ApiInboxArchiveAllReadRoute,
  ApiInboxArchiveCompletedRoute: ApiInboxArchiveCompletedRoute,
  ApiInboxMarkAllReadRoute: ApiInboxMarkAllReadRoute,
  ApiInboxUnreadCountRoute: ApiInboxUnreadCountRoute,
  ApiInboxIdArchiveRoute: ApiInboxIdArchiveRoute,
  ApiInboxIdReadRoute: ApiInboxIdReadRoute,
}

const ApiInboxRouteWithChildren = ApiInboxRoute._addFileChildren(
  ApiInboxRouteChildren,
)

interface ApiInvitationsIdRouteChildren {
  ApiInvitationsIdAcceptRoute: typeof ApiInvitationsIdAcceptRoute
  ApiInvitationsIdDeclineRoute: typeof ApiInvitationsIdDeclineRoute
}

const ApiInvitationsIdRouteChildren: ApiInvitationsIdRouteChildren = {
  ApiInvitationsIdAcceptRoute: ApiInvitationsIdAcceptRoute,
  ApiInvitationsIdDeclineRoute: ApiInvitationsIdDeclineRoute,
}

const ApiInvitationsIdRouteWithChildren =
  ApiInvitationsIdRoute._addFileChildren(ApiInvitationsIdRouteChildren)

interface ApiInvitationsRouteChildren {
  ApiInvitationsIdRoute: typeof ApiInvitationsIdRouteWithChildren
}

const ApiInvitationsRouteChildren: ApiInvitationsRouteChildren = {
  ApiInvitationsIdRoute: ApiInvitationsIdRouteWithChildren,
}

const ApiInvitationsRouteWithChildren = ApiInvitationsRoute._addFileChildren(
  ApiInvitationsRouteChildren,
)

interface ApiIssuesIdSourceBindingsRouteChildren {
  ApiIssuesIdSourceBindingsBindingIdRoute: typeof ApiIssuesIdSourceBindingsBindingIdRoute
}

const ApiIssuesIdSourceBindingsRouteChildren: ApiIssuesIdSourceBindingsRouteChildren =
  {
    ApiIssuesIdSourceBindingsBindingIdRoute:
      ApiIssuesIdSourceBindingsBindingIdRoute,
  }

const ApiIssuesIdSourceBindingsRouteWithChildren =
  ApiIssuesIdSourceBindingsRoute._addFileChildren(
    ApiIssuesIdSourceBindingsRouteChildren,
  )

interface ApiIssuesIdRouteChildren {
  ApiIssuesIdActiveRunRoute: typeof ApiIssuesIdActiveRunRoute
  ApiIssuesIdCancelRoute: typeof ApiIssuesIdCancelRoute
  ApiIssuesIdCommentsRoute: typeof ApiIssuesIdCommentsRoute
  ApiIssuesIdEventsRoute: typeof ApiIssuesIdEventsRoute
  ApiIssuesIdReactionsRoute: typeof ApiIssuesIdReactionsRoute
  ApiIssuesIdRunsRoute: typeof ApiIssuesIdRunsRoute
  ApiIssuesIdSourceBindingsRoute: typeof ApiIssuesIdSourceBindingsRouteWithChildren
  ApiIssuesIdSubscribeRoute: typeof ApiIssuesIdSubscribeRoute
  ApiIssuesIdSubscribersRoute: typeof ApiIssuesIdSubscribersRoute
  ApiIssuesIdTimelineRoute: typeof ApiIssuesIdTimelineRoute
  ApiIssuesIdUnsubscribeRoute: typeof ApiIssuesIdUnsubscribeRoute
  ApiIssuesIdUsageRoute: typeof ApiIssuesIdUsageRoute
  ApiIssuesIdWorkProductsRoute: typeof ApiIssuesIdWorkProductsRoute
}

const ApiIssuesIdRouteChildren: ApiIssuesIdRouteChildren = {
  ApiIssuesIdActiveRunRoute: ApiIssuesIdActiveRunRoute,
  ApiIssuesIdCancelRoute: ApiIssuesIdCancelRoute,
  ApiIssuesIdCommentsRoute: ApiIssuesIdCommentsRoute,
  ApiIssuesIdEventsRoute: ApiIssuesIdEventsRoute,
  ApiIssuesIdReactionsRoute: ApiIssuesIdReactionsRoute,
  ApiIssuesIdRunsRoute: ApiIssuesIdRunsRoute,
  ApiIssuesIdSourceBindingsRoute: ApiIssuesIdSourceBindingsRouteWithChildren,
  ApiIssuesIdSubscribeRoute: ApiIssuesIdSubscribeRoute,
  ApiIssuesIdSubscribersRoute: ApiIssuesIdSubscribersRoute,
  ApiIssuesIdTimelineRoute: ApiIssuesIdTimelineRoute,
  ApiIssuesIdUnsubscribeRoute: ApiIssuesIdUnsubscribeRoute,
  ApiIssuesIdUsageRoute: ApiIssuesIdUsageRoute,
  ApiIssuesIdWorkProductsRoute: ApiIssuesIdWorkProductsRoute,
}

const ApiIssuesIdRouteWithChildren = ApiIssuesIdRoute._addFileChildren(
  ApiIssuesIdRouteChildren,
)

interface ApiIssuesRouteChildren {
  ApiIssuesIdRoute: typeof ApiIssuesIdRouteWithChildren
  ApiIssuesChildProgressRoute: typeof ApiIssuesChildProgressRoute
  ApiIssuesSearchRoute: typeof ApiIssuesSearchRoute
}

const ApiIssuesRouteChildren: ApiIssuesRouteChildren = {
  ApiIssuesIdRoute: ApiIssuesIdRouteWithChildren,
  ApiIssuesChildProgressRoute: ApiIssuesChildProgressRoute,
  ApiIssuesSearchRoute: ApiIssuesSearchRoute,
}

const ApiIssuesRouteWithChildren = ApiIssuesRoute._addFileChildren(
  ApiIssuesRouteChildren,
)

interface ApiSkillsRouteChildren {
  ApiSkillsIdRoute: typeof ApiSkillsIdRoute
  ApiSkillsImportRoute: typeof ApiSkillsImportRoute
  ApiSkillsPreviewRoute: typeof ApiSkillsPreviewRoute
  ApiSkillsSearchRoute: typeof ApiSkillsSearchRoute
}

const ApiSkillsRouteChildren: ApiSkillsRouteChildren = {
  ApiSkillsIdRoute: ApiSkillsIdRoute,
  ApiSkillsImportRoute: ApiSkillsImportRoute,
  ApiSkillsPreviewRoute: ApiSkillsPreviewRoute,
  ApiSkillsSearchRoute: ApiSkillsSearchRoute,
}

const ApiSkillsRouteWithChildren = ApiSkillsRoute._addFileChildren(
  ApiSkillsRouteChildren,
)

interface ApiWorkspacesIdInvitationsRouteChildren {
  ApiWorkspacesIdInvitationsInvitationIdRoute: typeof ApiWorkspacesIdInvitationsInvitationIdRoute
}

const ApiWorkspacesIdInvitationsRouteChildren: ApiWorkspacesIdInvitationsRouteChildren =
  {
    ApiWorkspacesIdInvitationsInvitationIdRoute:
      ApiWorkspacesIdInvitationsInvitationIdRoute,
  }

const ApiWorkspacesIdInvitationsRouteWithChildren =
  ApiWorkspacesIdInvitationsRoute._addFileChildren(
    ApiWorkspacesIdInvitationsRouteChildren,
  )

interface ApiWorkspacesIdMembersRouteChildren {
  ApiWorkspacesIdMembersMemberIdRoute: typeof ApiWorkspacesIdMembersMemberIdRoute
}

const ApiWorkspacesIdMembersRouteChildren: ApiWorkspacesIdMembersRouteChildren =
  {
    ApiWorkspacesIdMembersMemberIdRoute: ApiWorkspacesIdMembersMemberIdRoute,
  }

const ApiWorkspacesIdMembersRouteWithChildren =
  ApiWorkspacesIdMembersRoute._addFileChildren(
    ApiWorkspacesIdMembersRouteChildren,
  )

interface ApiWorkspacesIdRouteChildren {
  ApiWorkspacesIdInvitationsRoute: typeof ApiWorkspacesIdInvitationsRouteWithChildren
  ApiWorkspacesIdMembersRoute: typeof ApiWorkspacesIdMembersRouteWithChildren
}

const ApiWorkspacesIdRouteChildren: ApiWorkspacesIdRouteChildren = {
  ApiWorkspacesIdInvitationsRoute: ApiWorkspacesIdInvitationsRouteWithChildren,
  ApiWorkspacesIdMembersRoute: ApiWorkspacesIdMembersRouteWithChildren,
}

const ApiWorkspacesIdRouteWithChildren = ApiWorkspacesIdRoute._addFileChildren(
  ApiWorkspacesIdRouteChildren,
)

interface ApiWorkspacesRouteChildren {
  ApiWorkspacesIdRoute: typeof ApiWorkspacesIdRouteWithChildren
}

const ApiWorkspacesRouteChildren: ApiWorkspacesRouteChildren = {
  ApiWorkspacesIdRoute: ApiWorkspacesIdRouteWithChildren,
}

const ApiWorkspacesRouteWithChildren = ApiWorkspacesRoute._addFileChildren(
  ApiWorkspacesRouteChildren,
)

interface ApiChatThreadsIdRouteChildren {
  ApiChatThreadsIdDocumentsRoute: typeof ApiChatThreadsIdDocumentsRoute
  ApiChatThreadsIdPrimaryIssueRoute: typeof ApiChatThreadsIdPrimaryIssueRoute
  ApiChatThreadsIdToolApprovalRoute: typeof ApiChatThreadsIdToolApprovalRoute
}

const ApiChatThreadsIdRouteChildren: ApiChatThreadsIdRouteChildren = {
  ApiChatThreadsIdDocumentsRoute: ApiChatThreadsIdDocumentsRoute,
  ApiChatThreadsIdPrimaryIssueRoute: ApiChatThreadsIdPrimaryIssueRoute,
  ApiChatThreadsIdToolApprovalRoute: ApiChatThreadsIdToolApprovalRoute,
}

const ApiChatThreadsIdRouteWithChildren =
  ApiChatThreadsIdRoute._addFileChildren(ApiChatThreadsIdRouteChildren)

interface ApiChatThreadsRouteChildren {
  ApiChatThreadsIdRoute: typeof ApiChatThreadsIdRouteWithChildren
}

const ApiChatThreadsRouteChildren: ApiChatThreadsRouteChildren = {
  ApiChatThreadsIdRoute: ApiChatThreadsIdRouteWithChildren,
}

const ApiChatThreadsRouteWithChildren = ApiChatThreadsRoute._addFileChildren(
  ApiChatThreadsRouteChildren,
)

interface ApiCommentsIdRouteChildren {
  ApiCommentsIdReactionsRoute: typeof ApiCommentsIdReactionsRoute
}

const ApiCommentsIdRouteChildren: ApiCommentsIdRouteChildren = {
  ApiCommentsIdReactionsRoute: ApiCommentsIdReactionsRoute,
}

const ApiCommentsIdRouteWithChildren = ApiCommentsIdRoute._addFileChildren(
  ApiCommentsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAgentsRoute: ApiAgentsRouteWithChildren,
  ApiAutomationsRoute: ApiAutomationsRouteWithChildren,
  ApiConnectionsRoute: ApiConnectionsRouteWithChildren,
  ApiDebugStreamRoute: ApiDebugStreamRoute,
  ApiInboxRoute: ApiInboxRouteWithChildren,
  ApiInvitationsRoute: ApiInvitationsRouteWithChildren,
  ApiIssuesRoute: ApiIssuesRouteWithChildren,
  ApiMeRoute: ApiMeRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiRuntimesRoute: ApiRuntimesRoute,
  ApiSkillsRoute: ApiSkillsRouteWithChildren,
  ApiWorkspacesRoute: ApiWorkspacesRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatThreadsRoute: ApiChatThreadsRouteWithChildren,
  ApiCommentsIdRoute: ApiCommentsIdRouteWithChildren,
  ApiDevIssueRunPlanRoute: ApiDevIssueRunPlanRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubInstallRoute: ApiGithubInstallRoute,
  ApiGithubSetupRoute: ApiGithubSetupRoute,
  ApiInternalCapabilitySyncRoute: ApiInternalCapabilitySyncRoute,
  ApiRunsIdRoute: ApiRunsIdRoute,
  ApiDocumentsIdDisplayRoute: ApiDocumentsIdDisplayRoute,
  ApiDocumentsIdDocxRoute: ApiDocumentsIdDocxRoute,
  ApiDocumentsIdMetadataRoute: ApiDocumentsIdMetadataRoute,
  ApiDocumentsIdTrackedChangeIdsRoute: ApiDocumentsIdTrackedChangeIdsRoute,
  ApiDocumentsIdVersionsRoute: ApiDocumentsIdVersionsRoute,
  ApiPermissionRequestsIdResolveRoute: ApiPermissionRequestsIdResolveRoute,
  ApiWorkProductsIdReviewRoute: ApiWorkProductsIdReviewRoute,
  ApiDocumentsDocumentIdEditsEditIdActionRoute:
    ApiDocumentsDocumentIdEditsEditIdActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
