/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkspacesRouteImport } from './routes/api/workspaces'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiRuntimesRouteImport } from './routes/api/runtimes'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiIssuesRouteImport } from './routes/api/issues'
import { Route as ApiInvitationsRouteImport } from './routes/api/invitations'
import { Route as ApiInboxRouteImport } from './routes/api/inbox'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiBootstrapRouteImport } from './routes/api/bootstrap'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as ApiWorkspacesIdRouteImport } from './routes/api/workspaces/$id'
import { Route as ApiSkillsIdRouteImport } from './routes/api/skills/$id'
import { Route as ApiIssuesSearchRouteImport } from './routes/api/issues/search'
import { Route as ApiIssuesChildProgressRouteImport } from './routes/api/issues/child-progress'
import { Route as ApiInvitationsIdRouteImport } from './routes/api/invitations/$id'
import { Route as ApiInboxUnreadCountRouteImport } from './routes/api/inbox/unread-count'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentsIdRouteImport } from './routes/api/agents/$id'
import { Route as ApiWorkspacesIdMembersRouteImport } from './routes/api/workspaces/$id/members'
import { Route as ApiWorkspacesIdInvitationsRouteImport } from './routes/api/workspaces/$id/invitations'
import { Route as ApiInvitationsIdDeclineRouteImport } from './routes/api/invitations/$id/decline'
import { Route as ApiInvitationsIdAcceptRouteImport } from './routes/api/invitations/$id/accept'
import { Route as ApiAgentsIdRestoreRouteImport } from './routes/api/agents/$id/restore'
import { Route as ApiAgentsIdArchiveRouteImport } from './routes/api/agents/$id/archive'
import { Route as ApiWorkspacesIdMembersMemberIdRouteImport } from './routes/api/workspaces/$id/members/$memberId'
import { Route as ApiWorkspacesIdInvitationsInvitationIdRouteImport } from './routes/api/workspaces/$id/invitations/$invitationId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesRoute = ApiWorkspacesRouteImport.update({
  id: '/api/workspaces',
  path: '/api/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimesRoute = ApiRuntimesRouteImport.update({
  id: '/api/runtimes',
  path: '/api/runtimes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIssuesRoute = ApiIssuesRouteImport.update({
  id: '/api/issues',
  path: '/api/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsRoute = ApiInvitationsRouteImport.update({
  id: '/api/invitations',
  path: '/api/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBootstrapRoute = ApiBootstrapRouteImport.update({
  id: '/api/bootstrap',
  path: '/api/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiWorkspacesIdRoute = ApiWorkspacesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWorkspacesRoute,
} as any)
const ApiSkillsIdRoute = ApiSkillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiIssuesSearchRoute = ApiIssuesSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiIssuesChildProgressRoute = ApiIssuesChildProgressRouteImport.update({
  id: '/child-progress',
  path: '/child-progress',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiInvitationsIdRoute = ApiInvitationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvitationsRoute,
} as any)
const ApiInboxUnreadCountRoute = ApiInboxUnreadCountRouteImport.update({
  id: '/unread-count',
  path: '/unread-count',
  getParentRoute: () => ApiInboxRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIdRoute = ApiAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAgentsRoute,
} as any)
const ApiWorkspacesIdMembersRoute = ApiWorkspacesIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiWorkspacesIdRoute,
} as any)
const ApiWorkspacesIdInvitationsRoute =
  ApiWorkspacesIdInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => ApiWorkspacesIdRoute,
  } as any)
const ApiInvitationsIdDeclineRoute = ApiInvitationsIdDeclineRouteImport.update({
  id: '/decline',
  path: '/decline',
  getParentRoute: () => ApiInvitationsIdRoute,
} as any)
const ApiInvitationsIdAcceptRoute = ApiInvitationsIdAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => ApiInvitationsIdRoute,
} as any)
const ApiAgentsIdRestoreRoute = ApiAgentsIdRestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => ApiAgentsIdRoute,
} as any)
const ApiAgentsIdArchiveRoute = ApiAgentsIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ApiAgentsIdRoute,
} as any)
const ApiWorkspacesIdMembersMemberIdRoute =
  ApiWorkspacesIdMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => ApiWorkspacesIdMembersRoute,
  } as any)
const ApiWorkspacesIdInvitationsInvitationIdRoute =
  ApiWorkspacesIdInvitationsInvitationIdRouteImport.update({
    id: '/$invitationId',
    path: '/$invitationId',
    getParentRoute: () => ApiWorkspacesIdInvitationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/api/config': typeof ApiConfigRoute
  '/api/inbox': typeof ApiInboxRouteWithChildren
  '/api/invitations': typeof ApiInvitationsRouteWithChildren
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/runtimes': typeof ApiRuntimesRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/api/agents/$id': typeof ApiAgentsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/inbox/unread-count': typeof ApiInboxUnreadCountRoute
  '/api/invitations/$id': typeof ApiInvitationsIdRouteWithChildren
  '/api/issues/child-progress': typeof ApiIssuesChildProgressRoute
  '/api/issues/search': typeof ApiIssuesSearchRoute
  '/api/skills/$id': typeof ApiSkillsIdRoute
  '/api/workspaces/$id': typeof ApiWorkspacesIdRouteWithChildren
  '/api/agents/$id/archive': typeof ApiAgentsIdArchiveRoute
  '/api/agents/$id/restore': typeof ApiAgentsIdRestoreRoute
  '/api/invitations/$id/accept': typeof ApiInvitationsIdAcceptRoute
  '/api/invitations/$id/decline': typeof ApiInvitationsIdDeclineRoute
  '/api/workspaces/$id/invitations': typeof ApiWorkspacesIdInvitationsRouteWithChildren
  '/api/workspaces/$id/members': typeof ApiWorkspacesIdMembersRouteWithChildren
  '/api/workspaces/$id/invitations/$invitationId': typeof ApiWorkspacesIdInvitationsInvitationIdRoute
  '/api/workspaces/$id/members/$memberId': typeof ApiWorkspacesIdMembersMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/api/config': typeof ApiConfigRoute
  '/api/inbox': typeof ApiInboxRouteWithChildren
  '/api/invitations': typeof ApiInvitationsRouteWithChildren
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/runtimes': typeof ApiRuntimesRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/api/agents/$id': typeof ApiAgentsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/inbox/unread-count': typeof ApiInboxUnreadCountRoute
  '/api/invitations/$id': typeof ApiInvitationsIdRouteWithChildren
  '/api/issues/child-progress': typeof ApiIssuesChildProgressRoute
  '/api/issues/search': typeof ApiIssuesSearchRoute
  '/api/skills/$id': typeof ApiSkillsIdRoute
  '/api/workspaces/$id': typeof ApiWorkspacesIdRouteWithChildren
  '/api/agents/$id/archive': typeof ApiAgentsIdArchiveRoute
  '/api/agents/$id/restore': typeof ApiAgentsIdRestoreRoute
  '/api/invitations/$id/accept': typeof ApiInvitationsIdAcceptRoute
  '/api/invitations/$id/decline': typeof ApiInvitationsIdDeclineRoute
  '/api/workspaces/$id/invitations': typeof ApiWorkspacesIdInvitationsRouteWithChildren
  '/api/workspaces/$id/members': typeof ApiWorkspacesIdMembersRouteWithChildren
  '/api/workspaces/$id/invitations/$invitationId': typeof ApiWorkspacesIdInvitationsInvitationIdRoute
  '/api/workspaces/$id/members/$memberId': typeof ApiWorkspacesIdMembersMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/api/config': typeof ApiConfigRoute
  '/api/inbox': typeof ApiInboxRouteWithChildren
  '/api/invitations': typeof ApiInvitationsRouteWithChildren
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/runtimes': typeof ApiRuntimesRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/api/agents/$id': typeof ApiAgentsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/inbox/unread-count': typeof ApiInboxUnreadCountRoute
  '/api/invitations/$id': typeof ApiInvitationsIdRouteWithChildren
  '/api/issues/child-progress': typeof ApiIssuesChildProgressRoute
  '/api/issues/search': typeof ApiIssuesSearchRoute
  '/api/skills/$id': typeof ApiSkillsIdRoute
  '/api/workspaces/$id': typeof ApiWorkspacesIdRouteWithChildren
  '/api/agents/$id/archive': typeof ApiAgentsIdArchiveRoute
  '/api/agents/$id/restore': typeof ApiAgentsIdRestoreRoute
  '/api/invitations/$id/accept': typeof ApiInvitationsIdAcceptRoute
  '/api/invitations/$id/decline': typeof ApiInvitationsIdDeclineRoute
  '/api/workspaces/$id/invitations': typeof ApiWorkspacesIdInvitationsRouteWithChildren
  '/api/workspaces/$id/members': typeof ApiWorkspacesIdMembersRouteWithChildren
  '/api/workspaces/$id/invitations/$invitationId': typeof ApiWorkspacesIdInvitationsInvitationIdRoute
  '/api/workspaces/$id/members/$memberId': typeof ApiWorkspacesIdMembersMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/api/agents'
    | '/api/bootstrap'
    | '/api/config'
    | '/api/inbox'
    | '/api/invitations'
    | '/api/issues'
    | '/api/me'
    | '/api/runtimes'
    | '/api/skills'
    | '/api/workspaces'
    | '/api/agents/$id'
    | '/api/auth/$'
    | '/api/inbox/unread-count'
    | '/api/invitations/$id'
    | '/api/issues/child-progress'
    | '/api/issues/search'
    | '/api/skills/$id'
    | '/api/workspaces/$id'
    | '/api/agents/$id/archive'
    | '/api/agents/$id/restore'
    | '/api/invitations/$id/accept'
    | '/api/invitations/$id/decline'
    | '/api/workspaces/$id/invitations'
    | '/api/workspaces/$id/members'
    | '/api/workspaces/$id/invitations/$invitationId'
    | '/api/workspaces/$id/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/api/agents'
    | '/api/bootstrap'
    | '/api/config'
    | '/api/inbox'
    | '/api/invitations'
    | '/api/issues'
    | '/api/me'
    | '/api/runtimes'
    | '/api/skills'
    | '/api/workspaces'
    | '/api/agents/$id'
    | '/api/auth/$'
    | '/api/inbox/unread-count'
    | '/api/invitations/$id'
    | '/api/issues/child-progress'
    | '/api/issues/search'
    | '/api/skills/$id'
    | '/api/workspaces/$id'
    | '/api/agents/$id/archive'
    | '/api/agents/$id/restore'
    | '/api/invitations/$id/accept'
    | '/api/invitations/$id/decline'
    | '/api/workspaces/$id/invitations'
    | '/api/workspaces/$id/members'
    | '/api/workspaces/$id/invitations/$invitationId'
    | '/api/workspaces/$id/members/$memberId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/workspace'
    | '/api/agents'
    | '/api/bootstrap'
    | '/api/config'
    | '/api/inbox'
    | '/api/invitations'
    | '/api/issues'
    | '/api/me'
    | '/api/runtimes'
    | '/api/skills'
    | '/api/workspaces'
    | '/api/agents/$id'
    | '/api/auth/$'
    | '/api/inbox/unread-count'
    | '/api/invitations/$id'
    | '/api/issues/child-progress'
    | '/api/issues/search'
    | '/api/skills/$id'
    | '/api/workspaces/$id'
    | '/api/agents/$id/archive'
    | '/api/agents/$id/restore'
    | '/api/invitations/$id/accept'
    | '/api/invitations/$id/decline'
    | '/api/workspaces/$id/invitations'
    | '/api/workspaces/$id/members'
    | '/api/workspaces/$id/invitations/$invitationId'
    | '/api/workspaces/$id/members/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAgentsRoute: typeof ApiAgentsRouteWithChildren
  ApiBootstrapRoute: typeof ApiBootstrapRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiInboxRoute: typeof ApiInboxRouteWithChildren
  ApiInvitationsRoute: typeof ApiInvitationsRouteWithChildren
  ApiIssuesRoute: typeof ApiIssuesRouteWithChildren
  ApiMeRoute: typeof ApiMeRoute
  ApiRuntimesRoute: typeof ApiRuntimesRoute
  ApiSkillsRoute: typeof ApiSkillsRouteWithChildren
  ApiWorkspacesRoute: typeof ApiWorkspacesRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces': {
      id: '/api/workspaces'
      path: '/api/workspaces'
      fullPath: '/api/workspaces'
      preLoaderRoute: typeof ApiWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtimes': {
      id: '/api/runtimes'
      path: '/api/runtimes'
      fullPath: '/api/runtimes'
      preLoaderRoute: typeof ApiRuntimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/issues': {
      id: '/api/issues'
      path: '/api/issues'
      fullPath: '/api/issues'
      preLoaderRoute: typeof ApiIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations': {
      id: '/api/invitations'
      path: '/api/invitations'
      fullPath: '/api/invitations'
      preLoaderRoute: typeof ApiInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bootstrap': {
      id: '/api/bootstrap'
      path: '/api/bootstrap'
      fullPath: '/api/bootstrap'
      preLoaderRoute: typeof ApiBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/workspaces/$id': {
      id: '/api/workspaces/$id'
      path: '/$id'
      fullPath: '/api/workspaces/$id'
      preLoaderRoute: typeof ApiWorkspacesIdRouteImport
      parentRoute: typeof ApiWorkspacesRoute
    }
    '/api/skills/$id': {
      id: '/api/skills/$id'
      path: '/$id'
      fullPath: '/api/skills/$id'
      preLoaderRoute: typeof ApiSkillsIdRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/issues/search': {
      id: '/api/issues/search'
      path: '/search'
      fullPath: '/api/issues/search'
      preLoaderRoute: typeof ApiIssuesSearchRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/issues/child-progress': {
      id: '/api/issues/child-progress'
      path: '/child-progress'
      fullPath: '/api/issues/child-progress'
      preLoaderRoute: typeof ApiIssuesChildProgressRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/invitations/$id': {
      id: '/api/invitations/$id'
      path: '/$id'
      fullPath: '/api/invitations/$id'
      preLoaderRoute: typeof ApiInvitationsIdRouteImport
      parentRoute: typeof ApiInvitationsRoute
    }
    '/api/inbox/unread-count': {
      id: '/api/inbox/unread-count'
      path: '/unread-count'
      fullPath: '/api/inbox/unread-count'
      preLoaderRoute: typeof ApiInboxUnreadCountRouteImport
      parentRoute: typeof ApiInboxRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$id': {
      id: '/api/agents/$id'
      path: '/$id'
      fullPath: '/api/agents/$id'
      preLoaderRoute: typeof ApiAgentsIdRouteImport
      parentRoute: typeof ApiAgentsRoute
    }
    '/api/workspaces/$id/members': {
      id: '/api/workspaces/$id/members'
      path: '/members'
      fullPath: '/api/workspaces/$id/members'
      preLoaderRoute: typeof ApiWorkspacesIdMembersRouteImport
      parentRoute: typeof ApiWorkspacesIdRoute
    }
    '/api/workspaces/$id/invitations': {
      id: '/api/workspaces/$id/invitations'
      path: '/invitations'
      fullPath: '/api/workspaces/$id/invitations'
      preLoaderRoute: typeof ApiWorkspacesIdInvitationsRouteImport
      parentRoute: typeof ApiWorkspacesIdRoute
    }
    '/api/invitations/$id/decline': {
      id: '/api/invitations/$id/decline'
      path: '/decline'
      fullPath: '/api/invitations/$id/decline'
      preLoaderRoute: typeof ApiInvitationsIdDeclineRouteImport
      parentRoute: typeof ApiInvitationsIdRoute
    }
    '/api/invitations/$id/accept': {
      id: '/api/invitations/$id/accept'
      path: '/accept'
      fullPath: '/api/invitations/$id/accept'
      preLoaderRoute: typeof ApiInvitationsIdAcceptRouteImport
      parentRoute: typeof ApiInvitationsIdRoute
    }
    '/api/agents/$id/restore': {
      id: '/api/agents/$id/restore'
      path: '/restore'
      fullPath: '/api/agents/$id/restore'
      preLoaderRoute: typeof ApiAgentsIdRestoreRouteImport
      parentRoute: typeof ApiAgentsIdRoute
    }
    '/api/agents/$id/archive': {
      id: '/api/agents/$id/archive'
      path: '/archive'
      fullPath: '/api/agents/$id/archive'
      preLoaderRoute: typeof ApiAgentsIdArchiveRouteImport
      parentRoute: typeof ApiAgentsIdRoute
    }
    '/api/workspaces/$id/members/$memberId': {
      id: '/api/workspaces/$id/members/$memberId'
      path: '/$memberId'
      fullPath: '/api/workspaces/$id/members/$memberId'
      preLoaderRoute: typeof ApiWorkspacesIdMembersMemberIdRouteImport
      parentRoute: typeof ApiWorkspacesIdMembersRoute
    }
    '/api/workspaces/$id/invitations/$invitationId': {
      id: '/api/workspaces/$id/invitations/$invitationId'
      path: '/$invitationId'
      fullPath: '/api/workspaces/$id/invitations/$invitationId'
      preLoaderRoute: typeof ApiWorkspacesIdInvitationsInvitationIdRouteImport
      parentRoute: typeof ApiWorkspacesIdInvitationsRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiAgentsIdRouteChildren {
  ApiAgentsIdArchiveRoute: typeof ApiAgentsIdArchiveRoute
  ApiAgentsIdRestoreRoute: typeof ApiAgentsIdRestoreRoute
}

const ApiAgentsIdRouteChildren: ApiAgentsIdRouteChildren = {
  ApiAgentsIdArchiveRoute: ApiAgentsIdArchiveRoute,
  ApiAgentsIdRestoreRoute: ApiAgentsIdRestoreRoute,
}

const ApiAgentsIdRouteWithChildren = ApiAgentsIdRoute._addFileChildren(
  ApiAgentsIdRouteChildren,
)

interface ApiAgentsRouteChildren {
  ApiAgentsIdRoute: typeof ApiAgentsIdRouteWithChildren
}

const ApiAgentsRouteChildren: ApiAgentsRouteChildren = {
  ApiAgentsIdRoute: ApiAgentsIdRouteWithChildren,
}

const ApiAgentsRouteWithChildren = ApiAgentsRoute._addFileChildren(
  ApiAgentsRouteChildren,
)

interface ApiInboxRouteChildren {
  ApiInboxUnreadCountRoute: typeof ApiInboxUnreadCountRoute
}

const ApiInboxRouteChildren: ApiInboxRouteChildren = {
  ApiInboxUnreadCountRoute: ApiInboxUnreadCountRoute,
}

const ApiInboxRouteWithChildren = ApiInboxRoute._addFileChildren(
  ApiInboxRouteChildren,
)

interface ApiInvitationsIdRouteChildren {
  ApiInvitationsIdAcceptRoute: typeof ApiInvitationsIdAcceptRoute
  ApiInvitationsIdDeclineRoute: typeof ApiInvitationsIdDeclineRoute
}

const ApiInvitationsIdRouteChildren: ApiInvitationsIdRouteChildren = {
  ApiInvitationsIdAcceptRoute: ApiInvitationsIdAcceptRoute,
  ApiInvitationsIdDeclineRoute: ApiInvitationsIdDeclineRoute,
}

const ApiInvitationsIdRouteWithChildren =
  ApiInvitationsIdRoute._addFileChildren(ApiInvitationsIdRouteChildren)

interface ApiInvitationsRouteChildren {
  ApiInvitationsIdRoute: typeof ApiInvitationsIdRouteWithChildren
}

const ApiInvitationsRouteChildren: ApiInvitationsRouteChildren = {
  ApiInvitationsIdRoute: ApiInvitationsIdRouteWithChildren,
}

const ApiInvitationsRouteWithChildren = ApiInvitationsRoute._addFileChildren(
  ApiInvitationsRouteChildren,
)

interface ApiIssuesRouteChildren {
  ApiIssuesChildProgressRoute: typeof ApiIssuesChildProgressRoute
  ApiIssuesSearchRoute: typeof ApiIssuesSearchRoute
}

const ApiIssuesRouteChildren: ApiIssuesRouteChildren = {
  ApiIssuesChildProgressRoute: ApiIssuesChildProgressRoute,
  ApiIssuesSearchRoute: ApiIssuesSearchRoute,
}

const ApiIssuesRouteWithChildren = ApiIssuesRoute._addFileChildren(
  ApiIssuesRouteChildren,
)

interface ApiSkillsRouteChildren {
  ApiSkillsIdRoute: typeof ApiSkillsIdRoute
}

const ApiSkillsRouteChildren: ApiSkillsRouteChildren = {
  ApiSkillsIdRoute: ApiSkillsIdRoute,
}

const ApiSkillsRouteWithChildren = ApiSkillsRoute._addFileChildren(
  ApiSkillsRouteChildren,
)

interface ApiWorkspacesIdInvitationsRouteChildren {
  ApiWorkspacesIdInvitationsInvitationIdRoute: typeof ApiWorkspacesIdInvitationsInvitationIdRoute
}

const ApiWorkspacesIdInvitationsRouteChildren: ApiWorkspacesIdInvitationsRouteChildren =
  {
    ApiWorkspacesIdInvitationsInvitationIdRoute:
      ApiWorkspacesIdInvitationsInvitationIdRoute,
  }

const ApiWorkspacesIdInvitationsRouteWithChildren =
  ApiWorkspacesIdInvitationsRoute._addFileChildren(
    ApiWorkspacesIdInvitationsRouteChildren,
  )

interface ApiWorkspacesIdMembersRouteChildren {
  ApiWorkspacesIdMembersMemberIdRoute: typeof ApiWorkspacesIdMembersMemberIdRoute
}

const ApiWorkspacesIdMembersRouteChildren: ApiWorkspacesIdMembersRouteChildren =
  {
    ApiWorkspacesIdMembersMemberIdRoute: ApiWorkspacesIdMembersMemberIdRoute,
  }

const ApiWorkspacesIdMembersRouteWithChildren =
  ApiWorkspacesIdMembersRoute._addFileChildren(
    ApiWorkspacesIdMembersRouteChildren,
  )

interface ApiWorkspacesIdRouteChildren {
  ApiWorkspacesIdInvitationsRoute: typeof ApiWorkspacesIdInvitationsRouteWithChildren
  ApiWorkspacesIdMembersRoute: typeof ApiWorkspacesIdMembersRouteWithChildren
}

const ApiWorkspacesIdRouteChildren: ApiWorkspacesIdRouteChildren = {
  ApiWorkspacesIdInvitationsRoute: ApiWorkspacesIdInvitationsRouteWithChildren,
  ApiWorkspacesIdMembersRoute: ApiWorkspacesIdMembersRouteWithChildren,
}

const ApiWorkspacesIdRouteWithChildren = ApiWorkspacesIdRoute._addFileChildren(
  ApiWorkspacesIdRouteChildren,
)

interface ApiWorkspacesRouteChildren {
  ApiWorkspacesIdRoute: typeof ApiWorkspacesIdRouteWithChildren
}

const ApiWorkspacesRouteChildren: ApiWorkspacesRouteChildren = {
  ApiWorkspacesIdRoute: ApiWorkspacesIdRouteWithChildren,
}

const ApiWorkspacesRouteWithChildren = ApiWorkspacesRoute._addFileChildren(
  ApiWorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAgentsRoute: ApiAgentsRouteWithChildren,
  ApiBootstrapRoute: ApiBootstrapRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiInboxRoute: ApiInboxRouteWithChildren,
  ApiInvitationsRoute: ApiInvitationsRouteWithChildren,
  ApiIssuesRoute: ApiIssuesRouteWithChildren,
  ApiMeRoute: ApiMeRoute,
  ApiRuntimesRoute: ApiRuntimesRoute,
  ApiSkillsRoute: ApiSkillsRouteWithChildren,
  ApiWorkspacesRoute: ApiWorkspacesRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
