/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkspacesRouteImport } from './routes/api/workspaces'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiRuntimesRouteImport } from './routes/api/runtimes'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiIssuesRouteImport } from './routes/api/issues'
import { Route as ApiInvitationsRouteImport } from './routes/api/invitations'
import { Route as ApiInboxRouteImport } from './routes/api/inbox'
import { Route as ApiDebugStreamRouteImport } from './routes/api/debug-stream'
import { Route as ApiConnectionsRouteImport } from './routes/api/connections'
import { Route as ApiBootstrapRouteImport } from './routes/api/bootstrap'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as ApiWorkspacesIdRouteImport } from './routes/api/workspaces/$id'
import { Route as ApiSkillsSearchRouteImport } from './routes/api/skills/search'
import { Route as ApiSkillsPreviewRouteImport } from './routes/api/skills/preview'
import { Route as ApiSkillsImportRouteImport } from './routes/api/skills/import'
import { Route as ApiSkillsIdRouteImport } from './routes/api/skills/$id'
import { Route as ApiIssuesSearchRouteImport } from './routes/api/issues/search'
import { Route as ApiIssuesChildProgressRouteImport } from './routes/api/issues/child-progress'
import { Route as ApiIssuesIdRouteImport } from './routes/api/issues/$id'
import { Route as ApiInvitationsIdRouteImport } from './routes/api/invitations/$id'
import { Route as ApiInternalCapabilitySyncRouteImport } from './routes/api/internal/capability-sync'
import { Route as ApiInboxUnreadCountRouteImport } from './routes/api/inbox/unread-count'
import { Route as ApiGithubSetupRouteImport } from './routes/api/github/setup'
import { Route as ApiGithubInstallRouteImport } from './routes/api/github/install'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github/callback'
import { Route as ApiConnectionsConnectorIdRouteImport } from './routes/api/connections/$connectorId'
import { Route as ApiCommentsIdRouteImport } from './routes/api/comments/$id'
import { Route as ApiChatThreadsRouteImport } from './routes/api/chat/threads'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentsIdRouteImport } from './routes/api/agents/$id'
import { Route as ApiWorkspacesIdMembersRouteImport } from './routes/api/workspaces/$id/members'
import { Route as ApiWorkspacesIdInvitationsRouteImport } from './routes/api/workspaces/$id/invitations'
import { Route as ApiIssuesIdUsageRouteImport } from './routes/api/issues/$id/usage'
import { Route as ApiIssuesIdUnsubscribeRouteImport } from './routes/api/issues/$id/unsubscribe'
import { Route as ApiIssuesIdTimelineRouteImport } from './routes/api/issues/$id/timeline'
import { Route as ApiIssuesIdSubscribersRouteImport } from './routes/api/issues/$id/subscribers'
import { Route as ApiIssuesIdSubscribeRouteImport } from './routes/api/issues/$id/subscribe'
import { Route as ApiIssuesIdReactionsRouteImport } from './routes/api/issues/$id/reactions'
import { Route as ApiIssuesIdCommentsRouteImport } from './routes/api/issues/$id/comments'
import { Route as ApiInvitationsIdDeclineRouteImport } from './routes/api/invitations/$id/decline'
import { Route as ApiInvitationsIdAcceptRouteImport } from './routes/api/invitations/$id/accept'
import { Route as ApiConnectionsConnectorIdActivityRouteImport } from './routes/api/connections/$connectorId/activity'
import { Route as ApiCommentsIdReactionsRouteImport } from './routes/api/comments/$id/reactions'
import { Route as ApiChatThreadsIdRouteImport } from './routes/api/chat/threads/$id'
import { Route as ApiAgentsIdSkillsRouteImport } from './routes/api/agents/$id/skills'
import { Route as ApiAgentsIdRestoreRouteImport } from './routes/api/agents/$id/restore'
import { Route as ApiAgentsIdArchiveRouteImport } from './routes/api/agents/$id/archive'
import { Route as ApiWorkspacesIdMembersMemberIdRouteImport } from './routes/api/workspaces/$id/members/$memberId'
import { Route as ApiWorkspacesIdInvitationsInvitationIdRouteImport } from './routes/api/workspaces/$id/invitations/$invitationId'
import { Route as ApiChatThreadsIdToolApprovalRouteImport } from './routes/api/chat/threads/$id/tool-approval'
import { Route as ApiConnectionsConnectorIdToolsNameGrantRouteImport } from './routes/api/connections/$connectorId/tools/$name/grant'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesRoute = ApiWorkspacesRouteImport.update({
  id: '/api/workspaces',
  path: '/api/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimesRoute = ApiRuntimesRouteImport.update({
  id: '/api/runtimes',
  path: '/api/runtimes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIssuesRoute = ApiIssuesRouteImport.update({
  id: '/api/issues',
  path: '/api/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsRoute = ApiInvitationsRouteImport.update({
  id: '/api/invitations',
  path: '/api/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugStreamRoute = ApiDebugStreamRouteImport.update({
  id: '/api/debug-stream',
  path: '/api/debug-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsRoute = ApiConnectionsRouteImport.update({
  id: '/api/connections',
  path: '/api/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBootstrapRoute = ApiBootstrapRouteImport.update({
  id: '/api/bootstrap',
  path: '/api/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiWorkspacesIdRoute = ApiWorkspacesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWorkspacesRoute,
} as any)
const ApiSkillsSearchRoute = ApiSkillsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsPreviewRoute = ApiSkillsPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsImportRoute = ApiSkillsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsIdRoute = ApiSkillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiIssuesSearchRoute = ApiIssuesSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiIssuesChildProgressRoute = ApiIssuesChildProgressRouteImport.update({
  id: '/child-progress',
  path: '/child-progress',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiIssuesIdRoute = ApiIssuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiInvitationsIdRoute = ApiInvitationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvitationsRoute,
} as any)
const ApiInternalCapabilitySyncRoute =
  ApiInternalCapabilitySyncRouteImport.update({
    id: '/api/internal/capability-sync',
    path: '/api/internal/capability-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInboxUnreadCountRoute = ApiInboxUnreadCountRouteImport.update({
  id: '/unread-count',
  path: '/unread-count',
  getParentRoute: () => ApiInboxRoute,
} as any)
const ApiGithubSetupRoute = ApiGithubSetupRouteImport.update({
  id: '/api/github/setup',
  path: '/api/github/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallRoute = ApiGithubInstallRouteImport.update({
  id: '/api/github/install',
  path: '/api/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsConnectorIdRoute =
  ApiConnectionsConnectorIdRouteImport.update({
    id: '/$connectorId',
    path: '/$connectorId',
    getParentRoute: () => ApiConnectionsRoute,
  } as any)
const ApiCommentsIdRoute = ApiCommentsIdRouteImport.update({
  id: '/api/comments/$id',
  path: '/api/comments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatThreadsRoute = ApiChatThreadsRouteImport.update({
  id: '/api/chat/threads',
  path: '/api/chat/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIdRoute = ApiAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAgentsRoute,
} as any)
const ApiWorkspacesIdMembersRoute = ApiWorkspacesIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiWorkspacesIdRoute,
} as any)
const ApiWorkspacesIdInvitationsRoute =
  ApiWorkspacesIdInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => ApiWorkspacesIdRoute,
  } as any)
const ApiIssuesIdUsageRoute = ApiIssuesIdUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdUnsubscribeRoute = ApiIssuesIdUnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdTimelineRoute = ApiIssuesIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdSubscribersRoute = ApiIssuesIdSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdSubscribeRoute = ApiIssuesIdSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdReactionsRoute = ApiIssuesIdReactionsRouteImport.update({
  id: '/reactions',
  path: '/reactions',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiIssuesIdCommentsRoute = ApiIssuesIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiIssuesIdRoute,
} as any)
const ApiInvitationsIdDeclineRoute = ApiInvitationsIdDeclineRouteImport.update({
  id: '/decline',
  path: '/decline',
  getParentRoute: () => ApiInvitationsIdRoute,
} as any)
const ApiInvitationsIdAcceptRoute = ApiInvitationsIdAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => ApiInvitationsIdRoute,
} as any)
const ApiConnectionsConnectorIdActivityRoute =
  ApiConnectionsConnectorIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ApiConnectionsConnectorIdRoute,
  } as any)
const ApiCommentsIdReactionsRoute = ApiCommentsIdReactionsRouteImport.update({
  id: '/reactions',
  path: '/reactions',
  getParentRoute: () => ApiCommentsIdRoute,
} as any)
const ApiChatThreadsIdRoute = ApiChatThreadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiChatThreadsRoute,
} as any)
const ApiAgentsIdSkillsRoute = ApiAgentsIdSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ApiAgentsIdRoute,
} as any)
const ApiAgentsIdRestoreRoute = ApiAgentsIdRestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => ApiAgentsIdRoute,
} as any)
const ApiAgentsIdArchiveRoute = ApiAgentsIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ApiAgentsIdRoute,
} as any)
const ApiWorkspacesIdMembersMemberIdRoute =
  ApiWorkspacesIdMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => ApiWorkspacesIdMembersRoute,
  } as any)
const ApiWorkspacesIdInvitationsInvitationIdRoute =
  ApiWorkspacesIdInvitationsInvitationIdRouteImport.update({
    id: '/$invitationId',
    path: '/$invitationId',
    getParentRoute: () => ApiWorkspacesIdInvitationsRoute,
  } as any)
const ApiChatThreadsIdToolApprovalRoute =
  ApiChatThreadsIdToolApprovalRouteImport.update({
    id: '/tool-approval',
    path: '/tool-approval',
    getParentRoute: () => ApiChatThreadsIdRoute,
  } as any)
const ApiConnectionsConnectorIdToolsNameGrantRoute =
  ApiConnectionsConnectorIdToolsNameGrantRouteImport.update({
    id: '/tools/$name/grant',
    path: '/tools/$name/grant',
    getParentRoute: () => ApiConnectionsConnectorIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/api/connections': typeof ApiConnectionsRouteWithChildren
  '/api/debug-stream': typeof ApiDebugStreamRoute
  '/api/inbox': typeof ApiInboxRouteWithChildren
  '/api/invitations': typeof ApiInvitationsRouteWithChildren
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/runtimes': typeof ApiRuntimesRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/api/agents/$id': typeof ApiAgentsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/threads': typeof ApiChatThreadsRouteWithChildren
  '/api/comments/$id': typeof ApiCommentsIdRouteWithChildren
  '/api/connections/$connectorId': typeof ApiConnectionsConnectorIdRouteWithChildren
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/inbox/unread-count': typeof ApiInboxUnreadCountRoute
  '/api/internal/capability-sync': typeof ApiInternalCapabilitySyncRoute
  '/api/invitations/$id': typeof ApiInvitationsIdRouteWithChildren
  '/api/issues/$id': typeof ApiIssuesIdRouteWithChildren
  '/api/issues/child-progress': typeof ApiIssuesChildProgressRoute
  '/api/issues/search': typeof ApiIssuesSearchRoute
  '/api/skills/$id': typeof ApiSkillsIdRoute
  '/api/skills/import': typeof ApiSkillsImportRoute
  '/api/skills/preview': typeof ApiSkillsPreviewRoute
  '/api/skills/search': typeof ApiSkillsSearchRoute
  '/api/workspaces/$id': typeof ApiWorkspacesIdRouteWithChildren
  '/api/agents/$id/archive': typeof ApiAgentsIdArchiveRoute
  '/api/agents/$id/restore': typeof ApiAgentsIdRestoreRoute
  '/api/agents/$id/skills': typeof ApiAgentsIdSkillsRoute
  '/api/chat/threads/$id': typeof ApiChatThreadsIdRouteWithChildren
  '/api/comments/$id/reactions': typeof ApiCommentsIdReactionsRoute
  '/api/connections/$connectorId/activity': typeof ApiConnectionsConnectorIdActivityRoute
  '/api/invitations/$id/accept': typeof ApiInvitationsIdAcceptRoute
  '/api/invitations/$id/decline': typeof ApiInvitationsIdDeclineRoute
  '/api/issues/$id/comments': typeof ApiIssuesIdCommentsRoute
  '/api/issues/$id/reactions': typeof ApiIssuesIdReactionsRoute
  '/api/issues/$id/subscribe': typeof ApiIssuesIdSubscribeRoute
  '/api/issues/$id/subscribers': typeof ApiIssuesIdSubscribersRoute
  '/api/issues/$id/timeline': typeof ApiIssuesIdTimelineRoute
  '/api/issues/$id/unsubscribe': typeof ApiIssuesIdUnsubscribeRoute
  '/api/issues/$id/usage': typeof ApiIssuesIdUsageRoute
  '/api/workspaces/$id/invitations': typeof ApiWorkspacesIdInvitationsRouteWithChildren
  '/api/workspaces/$id/members': typeof ApiWorkspacesIdMembersRouteWithChildren
  '/api/chat/threads/$id/tool-approval': typeof ApiChatThreadsIdToolApprovalRoute
  '/api/workspaces/$id/invitations/$invitationId': typeof ApiWorkspacesIdInvitationsInvitationIdRoute
  '/api/workspaces/$id/members/$memberId': typeof ApiWorkspacesIdMembersMemberIdRoute
  '/api/connections/$connectorId/tools/$name/grant': typeof ApiConnectionsConnectorIdToolsNameGrantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/api/connections': typeof ApiConnectionsRouteWithChildren
  '/api/debug-stream': typeof ApiDebugStreamRoute
  '/api/inbox': typeof ApiInboxRouteWithChildren
  '/api/invitations': typeof ApiInvitationsRouteWithChildren
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/runtimes': typeof ApiRuntimesRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/api/agents/$id': typeof ApiAgentsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/threads': typeof ApiChatThreadsRouteWithChildren
  '/api/comments/$id': typeof ApiCommentsIdRouteWithChildren
  '/api/connections/$connectorId': typeof ApiConnectionsConnectorIdRouteWithChildren
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/inbox/unread-count': typeof ApiInboxUnreadCountRoute
  '/api/internal/capability-sync': typeof ApiInternalCapabilitySyncRoute
  '/api/invitations/$id': typeof ApiInvitationsIdRouteWithChildren
  '/api/issues/$id': typeof ApiIssuesIdRouteWithChildren
  '/api/issues/child-progress': typeof ApiIssuesChildProgressRoute
  '/api/issues/search': typeof ApiIssuesSearchRoute
  '/api/skills/$id': typeof ApiSkillsIdRoute
  '/api/skills/import': typeof ApiSkillsImportRoute
  '/api/skills/preview': typeof ApiSkillsPreviewRoute
  '/api/skills/search': typeof ApiSkillsSearchRoute
  '/api/workspaces/$id': typeof ApiWorkspacesIdRouteWithChildren
  '/api/agents/$id/archive': typeof ApiAgentsIdArchiveRoute
  '/api/agents/$id/restore': typeof ApiAgentsIdRestoreRoute
  '/api/agents/$id/skills': typeof ApiAgentsIdSkillsRoute
  '/api/chat/threads/$id': typeof ApiChatThreadsIdRouteWithChildren
  '/api/comments/$id/reactions': typeof ApiCommentsIdReactionsRoute
  '/api/connections/$connectorId/activity': typeof ApiConnectionsConnectorIdActivityRoute
  '/api/invitations/$id/accept': typeof ApiInvitationsIdAcceptRoute
  '/api/invitations/$id/decline': typeof ApiInvitationsIdDeclineRoute
  '/api/issues/$id/comments': typeof ApiIssuesIdCommentsRoute
  '/api/issues/$id/reactions': typeof ApiIssuesIdReactionsRoute
  '/api/issues/$id/subscribe': typeof ApiIssuesIdSubscribeRoute
  '/api/issues/$id/subscribers': typeof ApiIssuesIdSubscribersRoute
  '/api/issues/$id/timeline': typeof ApiIssuesIdTimelineRoute
  '/api/issues/$id/unsubscribe': typeof ApiIssuesIdUnsubscribeRoute
  '/api/issues/$id/usage': typeof ApiIssuesIdUsageRoute
  '/api/workspaces/$id/invitations': typeof ApiWorkspacesIdInvitationsRouteWithChildren
  '/api/workspaces/$id/members': typeof ApiWorkspacesIdMembersRouteWithChildren
  '/api/chat/threads/$id/tool-approval': typeof ApiChatThreadsIdToolApprovalRoute
  '/api/workspaces/$id/invitations/$invitationId': typeof ApiWorkspacesIdInvitationsInvitationIdRoute
  '/api/workspaces/$id/members/$memberId': typeof ApiWorkspacesIdMembersMemberIdRoute
  '/api/connections/$connectorId/tools/$name/grant': typeof ApiConnectionsConnectorIdToolsNameGrantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/api/agents': typeof ApiAgentsRouteWithChildren
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/api/connections': typeof ApiConnectionsRouteWithChildren
  '/api/debug-stream': typeof ApiDebugStreamRoute
  '/api/inbox': typeof ApiInboxRouteWithChildren
  '/api/invitations': typeof ApiInvitationsRouteWithChildren
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/runtimes': typeof ApiRuntimesRoute
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/api/agents/$id': typeof ApiAgentsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/threads': typeof ApiChatThreadsRouteWithChildren
  '/api/comments/$id': typeof ApiCommentsIdRouteWithChildren
  '/api/connections/$connectorId': typeof ApiConnectionsConnectorIdRouteWithChildren
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/inbox/unread-count': typeof ApiInboxUnreadCountRoute
  '/api/internal/capability-sync': typeof ApiInternalCapabilitySyncRoute
  '/api/invitations/$id': typeof ApiInvitationsIdRouteWithChildren
  '/api/issues/$id': typeof ApiIssuesIdRouteWithChildren
  '/api/issues/child-progress': typeof ApiIssuesChildProgressRoute
  '/api/issues/search': typeof ApiIssuesSearchRoute
  '/api/skills/$id': typeof ApiSkillsIdRoute
  '/api/skills/import': typeof ApiSkillsImportRoute
  '/api/skills/preview': typeof ApiSkillsPreviewRoute
  '/api/skills/search': typeof ApiSkillsSearchRoute
  '/api/workspaces/$id': typeof ApiWorkspacesIdRouteWithChildren
  '/api/agents/$id/archive': typeof ApiAgentsIdArchiveRoute
  '/api/agents/$id/restore': typeof ApiAgentsIdRestoreRoute
  '/api/agents/$id/skills': typeof ApiAgentsIdSkillsRoute
  '/api/chat/threads/$id': typeof ApiChatThreadsIdRouteWithChildren
  '/api/comments/$id/reactions': typeof ApiCommentsIdReactionsRoute
  '/api/connections/$connectorId/activity': typeof ApiConnectionsConnectorIdActivityRoute
  '/api/invitations/$id/accept': typeof ApiInvitationsIdAcceptRoute
  '/api/invitations/$id/decline': typeof ApiInvitationsIdDeclineRoute
  '/api/issues/$id/comments': typeof ApiIssuesIdCommentsRoute
  '/api/issues/$id/reactions': typeof ApiIssuesIdReactionsRoute
  '/api/issues/$id/subscribe': typeof ApiIssuesIdSubscribeRoute
  '/api/issues/$id/subscribers': typeof ApiIssuesIdSubscribersRoute
  '/api/issues/$id/timeline': typeof ApiIssuesIdTimelineRoute
  '/api/issues/$id/unsubscribe': typeof ApiIssuesIdUnsubscribeRoute
  '/api/issues/$id/usage': typeof ApiIssuesIdUsageRoute
  '/api/workspaces/$id/invitations': typeof ApiWorkspacesIdInvitationsRouteWithChildren
  '/api/workspaces/$id/members': typeof ApiWorkspacesIdMembersRouteWithChildren
  '/api/chat/threads/$id/tool-approval': typeof ApiChatThreadsIdToolApprovalRoute
  '/api/workspaces/$id/invitations/$invitationId': typeof ApiWorkspacesIdInvitationsInvitationIdRoute
  '/api/workspaces/$id/members/$memberId': typeof ApiWorkspacesIdMembersMemberIdRoute
  '/api/connections/$connectorId/tools/$name/grant': typeof ApiConnectionsConnectorIdToolsNameGrantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/api/agents'
    | '/api/bootstrap'
    | '/api/connections'
    | '/api/debug-stream'
    | '/api/inbox'
    | '/api/invitations'
    | '/api/issues'
    | '/api/me'
    | '/api/projects'
    | '/api/runtimes'
    | '/api/skills'
    | '/api/workspaces'
    | '/api/agents/$id'
    | '/api/auth/$'
    | '/api/chat/threads'
    | '/api/comments/$id'
    | '/api/connections/$connectorId'
    | '/api/github/callback'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/inbox/unread-count'
    | '/api/internal/capability-sync'
    | '/api/invitations/$id'
    | '/api/issues/$id'
    | '/api/issues/child-progress'
    | '/api/issues/search'
    | '/api/skills/$id'
    | '/api/skills/import'
    | '/api/skills/preview'
    | '/api/skills/search'
    | '/api/workspaces/$id'
    | '/api/agents/$id/archive'
    | '/api/agents/$id/restore'
    | '/api/agents/$id/skills'
    | '/api/chat/threads/$id'
    | '/api/comments/$id/reactions'
    | '/api/connections/$connectorId/activity'
    | '/api/invitations/$id/accept'
    | '/api/invitations/$id/decline'
    | '/api/issues/$id/comments'
    | '/api/issues/$id/reactions'
    | '/api/issues/$id/subscribe'
    | '/api/issues/$id/subscribers'
    | '/api/issues/$id/timeline'
    | '/api/issues/$id/unsubscribe'
    | '/api/issues/$id/usage'
    | '/api/workspaces/$id/invitations'
    | '/api/workspaces/$id/members'
    | '/api/chat/threads/$id/tool-approval'
    | '/api/workspaces/$id/invitations/$invitationId'
    | '/api/workspaces/$id/members/$memberId'
    | '/api/connections/$connectorId/tools/$name/grant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace'
    | '/api/agents'
    | '/api/bootstrap'
    | '/api/connections'
    | '/api/debug-stream'
    | '/api/inbox'
    | '/api/invitations'
    | '/api/issues'
    | '/api/me'
    | '/api/projects'
    | '/api/runtimes'
    | '/api/skills'
    | '/api/workspaces'
    | '/api/agents/$id'
    | '/api/auth/$'
    | '/api/chat/threads'
    | '/api/comments/$id'
    | '/api/connections/$connectorId'
    | '/api/github/callback'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/inbox/unread-count'
    | '/api/internal/capability-sync'
    | '/api/invitations/$id'
    | '/api/issues/$id'
    | '/api/issues/child-progress'
    | '/api/issues/search'
    | '/api/skills/$id'
    | '/api/skills/import'
    | '/api/skills/preview'
    | '/api/skills/search'
    | '/api/workspaces/$id'
    | '/api/agents/$id/archive'
    | '/api/agents/$id/restore'
    | '/api/agents/$id/skills'
    | '/api/chat/threads/$id'
    | '/api/comments/$id/reactions'
    | '/api/connections/$connectorId/activity'
    | '/api/invitations/$id/accept'
    | '/api/invitations/$id/decline'
    | '/api/issues/$id/comments'
    | '/api/issues/$id/reactions'
    | '/api/issues/$id/subscribe'
    | '/api/issues/$id/subscribers'
    | '/api/issues/$id/timeline'
    | '/api/issues/$id/unsubscribe'
    | '/api/issues/$id/usage'
    | '/api/workspaces/$id/invitations'
    | '/api/workspaces/$id/members'
    | '/api/chat/threads/$id/tool-approval'
    | '/api/workspaces/$id/invitations/$invitationId'
    | '/api/workspaces/$id/members/$memberId'
    | '/api/connections/$connectorId/tools/$name/grant'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/workspace'
    | '/api/agents'
    | '/api/bootstrap'
    | '/api/connections'
    | '/api/debug-stream'
    | '/api/inbox'
    | '/api/invitations'
    | '/api/issues'
    | '/api/me'
    | '/api/projects'
    | '/api/runtimes'
    | '/api/skills'
    | '/api/workspaces'
    | '/api/agents/$id'
    | '/api/auth/$'
    | '/api/chat/threads'
    | '/api/comments/$id'
    | '/api/connections/$connectorId'
    | '/api/github/callback'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/inbox/unread-count'
    | '/api/internal/capability-sync'
    | '/api/invitations/$id'
    | '/api/issues/$id'
    | '/api/issues/child-progress'
    | '/api/issues/search'
    | '/api/skills/$id'
    | '/api/skills/import'
    | '/api/skills/preview'
    | '/api/skills/search'
    | '/api/workspaces/$id'
    | '/api/agents/$id/archive'
    | '/api/agents/$id/restore'
    | '/api/agents/$id/skills'
    | '/api/chat/threads/$id'
    | '/api/comments/$id/reactions'
    | '/api/connections/$connectorId/activity'
    | '/api/invitations/$id/accept'
    | '/api/invitations/$id/decline'
    | '/api/issues/$id/comments'
    | '/api/issues/$id/reactions'
    | '/api/issues/$id/subscribe'
    | '/api/issues/$id/subscribers'
    | '/api/issues/$id/timeline'
    | '/api/issues/$id/unsubscribe'
    | '/api/issues/$id/usage'
    | '/api/workspaces/$id/invitations'
    | '/api/workspaces/$id/members'
    | '/api/chat/threads/$id/tool-approval'
    | '/api/workspaces/$id/invitations/$invitationId'
    | '/api/workspaces/$id/members/$memberId'
    | '/api/connections/$connectorId/tools/$name/grant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAgentsRoute: typeof ApiAgentsRouteWithChildren
  ApiBootstrapRoute: typeof ApiBootstrapRoute
  ApiConnectionsRoute: typeof ApiConnectionsRouteWithChildren
  ApiDebugStreamRoute: typeof ApiDebugStreamRoute
  ApiInboxRoute: typeof ApiInboxRouteWithChildren
  ApiInvitationsRoute: typeof ApiInvitationsRouteWithChildren
  ApiIssuesRoute: typeof ApiIssuesRouteWithChildren
  ApiMeRoute: typeof ApiMeRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiRuntimesRoute: typeof ApiRuntimesRoute
  ApiSkillsRoute: typeof ApiSkillsRouteWithChildren
  ApiWorkspacesRoute: typeof ApiWorkspacesRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatThreadsRoute: typeof ApiChatThreadsRouteWithChildren
  ApiCommentsIdRoute: typeof ApiCommentsIdRouteWithChildren
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubInstallRoute: typeof ApiGithubInstallRoute
  ApiGithubSetupRoute: typeof ApiGithubSetupRoute
  ApiInternalCapabilitySyncRoute: typeof ApiInternalCapabilitySyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces': {
      id: '/api/workspaces'
      path: '/api/workspaces'
      fullPath: '/api/workspaces'
      preLoaderRoute: typeof ApiWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtimes': {
      id: '/api/runtimes'
      path: '/api/runtimes'
      fullPath: '/api/runtimes'
      preLoaderRoute: typeof ApiRuntimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/issues': {
      id: '/api/issues'
      path: '/api/issues'
      fullPath: '/api/issues'
      preLoaderRoute: typeof ApiIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations': {
      id: '/api/invitations'
      path: '/api/invitations'
      fullPath: '/api/invitations'
      preLoaderRoute: typeof ApiInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-stream': {
      id: '/api/debug-stream'
      path: '/api/debug-stream'
      fullPath: '/api/debug-stream'
      preLoaderRoute: typeof ApiDebugStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections': {
      id: '/api/connections'
      path: '/api/connections'
      fullPath: '/api/connections'
      preLoaderRoute: typeof ApiConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bootstrap': {
      id: '/api/bootstrap'
      path: '/api/bootstrap'
      fullPath: '/api/bootstrap'
      preLoaderRoute: typeof ApiBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/workspaces/$id': {
      id: '/api/workspaces/$id'
      path: '/$id'
      fullPath: '/api/workspaces/$id'
      preLoaderRoute: typeof ApiWorkspacesIdRouteImport
      parentRoute: typeof ApiWorkspacesRoute
    }
    '/api/skills/search': {
      id: '/api/skills/search'
      path: '/search'
      fullPath: '/api/skills/search'
      preLoaderRoute: typeof ApiSkillsSearchRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/preview': {
      id: '/api/skills/preview'
      path: '/preview'
      fullPath: '/api/skills/preview'
      preLoaderRoute: typeof ApiSkillsPreviewRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/import': {
      id: '/api/skills/import'
      path: '/import'
      fullPath: '/api/skills/import'
      preLoaderRoute: typeof ApiSkillsImportRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/$id': {
      id: '/api/skills/$id'
      path: '/$id'
      fullPath: '/api/skills/$id'
      preLoaderRoute: typeof ApiSkillsIdRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/issues/search': {
      id: '/api/issues/search'
      path: '/search'
      fullPath: '/api/issues/search'
      preLoaderRoute: typeof ApiIssuesSearchRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/issues/child-progress': {
      id: '/api/issues/child-progress'
      path: '/child-progress'
      fullPath: '/api/issues/child-progress'
      preLoaderRoute: typeof ApiIssuesChildProgressRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/issues/$id': {
      id: '/api/issues/$id'
      path: '/$id'
      fullPath: '/api/issues/$id'
      preLoaderRoute: typeof ApiIssuesIdRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/invitations/$id': {
      id: '/api/invitations/$id'
      path: '/$id'
      fullPath: '/api/invitations/$id'
      preLoaderRoute: typeof ApiInvitationsIdRouteImport
      parentRoute: typeof ApiInvitationsRoute
    }
    '/api/internal/capability-sync': {
      id: '/api/internal/capability-sync'
      path: '/api/internal/capability-sync'
      fullPath: '/api/internal/capability-sync'
      preLoaderRoute: typeof ApiInternalCapabilitySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox/unread-count': {
      id: '/api/inbox/unread-count'
      path: '/unread-count'
      fullPath: '/api/inbox/unread-count'
      preLoaderRoute: typeof ApiInboxUnreadCountRouteImport
      parentRoute: typeof ApiInboxRoute
    }
    '/api/github/setup': {
      id: '/api/github/setup'
      path: '/api/github/setup'
      fullPath: '/api/github/setup'
      preLoaderRoute: typeof ApiGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install': {
      id: '/api/github/install'
      path: '/api/github/install'
      fullPath: '/api/github/install'
      preLoaderRoute: typeof ApiGithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections/$connectorId': {
      id: '/api/connections/$connectorId'
      path: '/$connectorId'
      fullPath: '/api/connections/$connectorId'
      preLoaderRoute: typeof ApiConnectionsConnectorIdRouteImport
      parentRoute: typeof ApiConnectionsRoute
    }
    '/api/comments/$id': {
      id: '/api/comments/$id'
      path: '/api/comments/$id'
      fullPath: '/api/comments/$id'
      preLoaderRoute: typeof ApiCommentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/threads': {
      id: '/api/chat/threads'
      path: '/api/chat/threads'
      fullPath: '/api/chat/threads'
      preLoaderRoute: typeof ApiChatThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$id': {
      id: '/api/agents/$id'
      path: '/$id'
      fullPath: '/api/agents/$id'
      preLoaderRoute: typeof ApiAgentsIdRouteImport
      parentRoute: typeof ApiAgentsRoute
    }
    '/api/workspaces/$id/members': {
      id: '/api/workspaces/$id/members'
      path: '/members'
      fullPath: '/api/workspaces/$id/members'
      preLoaderRoute: typeof ApiWorkspacesIdMembersRouteImport
      parentRoute: typeof ApiWorkspacesIdRoute
    }
    '/api/workspaces/$id/invitations': {
      id: '/api/workspaces/$id/invitations'
      path: '/invitations'
      fullPath: '/api/workspaces/$id/invitations'
      preLoaderRoute: typeof ApiWorkspacesIdInvitationsRouteImport
      parentRoute: typeof ApiWorkspacesIdRoute
    }
    '/api/issues/$id/usage': {
      id: '/api/issues/$id/usage'
      path: '/usage'
      fullPath: '/api/issues/$id/usage'
      preLoaderRoute: typeof ApiIssuesIdUsageRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/unsubscribe': {
      id: '/api/issues/$id/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/api/issues/$id/unsubscribe'
      preLoaderRoute: typeof ApiIssuesIdUnsubscribeRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/timeline': {
      id: '/api/issues/$id/timeline'
      path: '/timeline'
      fullPath: '/api/issues/$id/timeline'
      preLoaderRoute: typeof ApiIssuesIdTimelineRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/subscribers': {
      id: '/api/issues/$id/subscribers'
      path: '/subscribers'
      fullPath: '/api/issues/$id/subscribers'
      preLoaderRoute: typeof ApiIssuesIdSubscribersRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/subscribe': {
      id: '/api/issues/$id/subscribe'
      path: '/subscribe'
      fullPath: '/api/issues/$id/subscribe'
      preLoaderRoute: typeof ApiIssuesIdSubscribeRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/reactions': {
      id: '/api/issues/$id/reactions'
      path: '/reactions'
      fullPath: '/api/issues/$id/reactions'
      preLoaderRoute: typeof ApiIssuesIdReactionsRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/issues/$id/comments': {
      id: '/api/issues/$id/comments'
      path: '/comments'
      fullPath: '/api/issues/$id/comments'
      preLoaderRoute: typeof ApiIssuesIdCommentsRouteImport
      parentRoute: typeof ApiIssuesIdRoute
    }
    '/api/invitations/$id/decline': {
      id: '/api/invitations/$id/decline'
      path: '/decline'
      fullPath: '/api/invitations/$id/decline'
      preLoaderRoute: typeof ApiInvitationsIdDeclineRouteImport
      parentRoute: typeof ApiInvitationsIdRoute
    }
    '/api/invitations/$id/accept': {
      id: '/api/invitations/$id/accept'
      path: '/accept'
      fullPath: '/api/invitations/$id/accept'
      preLoaderRoute: typeof ApiInvitationsIdAcceptRouteImport
      parentRoute: typeof ApiInvitationsIdRoute
    }
    '/api/connections/$connectorId/activity': {
      id: '/api/connections/$connectorId/activity'
      path: '/activity'
      fullPath: '/api/connections/$connectorId/activity'
      preLoaderRoute: typeof ApiConnectionsConnectorIdActivityRouteImport
      parentRoute: typeof ApiConnectionsConnectorIdRoute
    }
    '/api/comments/$id/reactions': {
      id: '/api/comments/$id/reactions'
      path: '/reactions'
      fullPath: '/api/comments/$id/reactions'
      preLoaderRoute: typeof ApiCommentsIdReactionsRouteImport
      parentRoute: typeof ApiCommentsIdRoute
    }
    '/api/chat/threads/$id': {
      id: '/api/chat/threads/$id'
      path: '/$id'
      fullPath: '/api/chat/threads/$id'
      preLoaderRoute: typeof ApiChatThreadsIdRouteImport
      parentRoute: typeof ApiChatThreadsRoute
    }
    '/api/agents/$id/skills': {
      id: '/api/agents/$id/skills'
      path: '/skills'
      fullPath: '/api/agents/$id/skills'
      preLoaderRoute: typeof ApiAgentsIdSkillsRouteImport
      parentRoute: typeof ApiAgentsIdRoute
    }
    '/api/agents/$id/restore': {
      id: '/api/agents/$id/restore'
      path: '/restore'
      fullPath: '/api/agents/$id/restore'
      preLoaderRoute: typeof ApiAgentsIdRestoreRouteImport
      parentRoute: typeof ApiAgentsIdRoute
    }
    '/api/agents/$id/archive': {
      id: '/api/agents/$id/archive'
      path: '/archive'
      fullPath: '/api/agents/$id/archive'
      preLoaderRoute: typeof ApiAgentsIdArchiveRouteImport
      parentRoute: typeof ApiAgentsIdRoute
    }
    '/api/workspaces/$id/members/$memberId': {
      id: '/api/workspaces/$id/members/$memberId'
      path: '/$memberId'
      fullPath: '/api/workspaces/$id/members/$memberId'
      preLoaderRoute: typeof ApiWorkspacesIdMembersMemberIdRouteImport
      parentRoute: typeof ApiWorkspacesIdMembersRoute
    }
    '/api/workspaces/$id/invitations/$invitationId': {
      id: '/api/workspaces/$id/invitations/$invitationId'
      path: '/$invitationId'
      fullPath: '/api/workspaces/$id/invitations/$invitationId'
      preLoaderRoute: typeof ApiWorkspacesIdInvitationsInvitationIdRouteImport
      parentRoute: typeof ApiWorkspacesIdInvitationsRoute
    }
    '/api/chat/threads/$id/tool-approval': {
      id: '/api/chat/threads/$id/tool-approval'
      path: '/tool-approval'
      fullPath: '/api/chat/threads/$id/tool-approval'
      preLoaderRoute: typeof ApiChatThreadsIdToolApprovalRouteImport
      parentRoute: typeof ApiChatThreadsIdRoute
    }
    '/api/connections/$connectorId/tools/$name/grant': {
      id: '/api/connections/$connectorId/tools/$name/grant'
      path: '/tools/$name/grant'
      fullPath: '/api/connections/$connectorId/tools/$name/grant'
      preLoaderRoute: typeof ApiConnectionsConnectorIdToolsNameGrantRouteImport
      parentRoute: typeof ApiConnectionsConnectorIdRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiAgentsIdRouteChildren {
  ApiAgentsIdArchiveRoute: typeof ApiAgentsIdArchiveRoute
  ApiAgentsIdRestoreRoute: typeof ApiAgentsIdRestoreRoute
  ApiAgentsIdSkillsRoute: typeof ApiAgentsIdSkillsRoute
}

const ApiAgentsIdRouteChildren: ApiAgentsIdRouteChildren = {
  ApiAgentsIdArchiveRoute: ApiAgentsIdArchiveRoute,
  ApiAgentsIdRestoreRoute: ApiAgentsIdRestoreRoute,
  ApiAgentsIdSkillsRoute: ApiAgentsIdSkillsRoute,
}

const ApiAgentsIdRouteWithChildren = ApiAgentsIdRoute._addFileChildren(
  ApiAgentsIdRouteChildren,
)

interface ApiAgentsRouteChildren {
  ApiAgentsIdRoute: typeof ApiAgentsIdRouteWithChildren
}

const ApiAgentsRouteChildren: ApiAgentsRouteChildren = {
  ApiAgentsIdRoute: ApiAgentsIdRouteWithChildren,
}

const ApiAgentsRouteWithChildren = ApiAgentsRoute._addFileChildren(
  ApiAgentsRouteChildren,
)

interface ApiConnectionsConnectorIdRouteChildren {
  ApiConnectionsConnectorIdActivityRoute: typeof ApiConnectionsConnectorIdActivityRoute
  ApiConnectionsConnectorIdToolsNameGrantRoute: typeof ApiConnectionsConnectorIdToolsNameGrantRoute
}

const ApiConnectionsConnectorIdRouteChildren: ApiConnectionsConnectorIdRouteChildren =
  {
    ApiConnectionsConnectorIdActivityRoute:
      ApiConnectionsConnectorIdActivityRoute,
    ApiConnectionsConnectorIdToolsNameGrantRoute:
      ApiConnectionsConnectorIdToolsNameGrantRoute,
  }

const ApiConnectionsConnectorIdRouteWithChildren =
  ApiConnectionsConnectorIdRoute._addFileChildren(
    ApiConnectionsConnectorIdRouteChildren,
  )

interface ApiConnectionsRouteChildren {
  ApiConnectionsConnectorIdRoute: typeof ApiConnectionsConnectorIdRouteWithChildren
}

const ApiConnectionsRouteChildren: ApiConnectionsRouteChildren = {
  ApiConnectionsConnectorIdRoute: ApiConnectionsConnectorIdRouteWithChildren,
}

const ApiConnectionsRouteWithChildren = ApiConnectionsRoute._addFileChildren(
  ApiConnectionsRouteChildren,
)

interface ApiInboxRouteChildren {
  ApiInboxUnreadCountRoute: typeof ApiInboxUnreadCountRoute
}

const ApiInboxRouteChildren: ApiInboxRouteChildren = {
  ApiInboxUnreadCountRoute: ApiInboxUnreadCountRoute,
}

const ApiInboxRouteWithChildren = ApiInboxRoute._addFileChildren(
  ApiInboxRouteChildren,
)

interface ApiInvitationsIdRouteChildren {
  ApiInvitationsIdAcceptRoute: typeof ApiInvitationsIdAcceptRoute
  ApiInvitationsIdDeclineRoute: typeof ApiInvitationsIdDeclineRoute
}

const ApiInvitationsIdRouteChildren: ApiInvitationsIdRouteChildren = {
  ApiInvitationsIdAcceptRoute: ApiInvitationsIdAcceptRoute,
  ApiInvitationsIdDeclineRoute: ApiInvitationsIdDeclineRoute,
}

const ApiInvitationsIdRouteWithChildren =
  ApiInvitationsIdRoute._addFileChildren(ApiInvitationsIdRouteChildren)

interface ApiInvitationsRouteChildren {
  ApiInvitationsIdRoute: typeof ApiInvitationsIdRouteWithChildren
}

const ApiInvitationsRouteChildren: ApiInvitationsRouteChildren = {
  ApiInvitationsIdRoute: ApiInvitationsIdRouteWithChildren,
}

const ApiInvitationsRouteWithChildren = ApiInvitationsRoute._addFileChildren(
  ApiInvitationsRouteChildren,
)

interface ApiIssuesIdRouteChildren {
  ApiIssuesIdCommentsRoute: typeof ApiIssuesIdCommentsRoute
  ApiIssuesIdReactionsRoute: typeof ApiIssuesIdReactionsRoute
  ApiIssuesIdSubscribeRoute: typeof ApiIssuesIdSubscribeRoute
  ApiIssuesIdSubscribersRoute: typeof ApiIssuesIdSubscribersRoute
  ApiIssuesIdTimelineRoute: typeof ApiIssuesIdTimelineRoute
  ApiIssuesIdUnsubscribeRoute: typeof ApiIssuesIdUnsubscribeRoute
  ApiIssuesIdUsageRoute: typeof ApiIssuesIdUsageRoute
}

const ApiIssuesIdRouteChildren: ApiIssuesIdRouteChildren = {
  ApiIssuesIdCommentsRoute: ApiIssuesIdCommentsRoute,
  ApiIssuesIdReactionsRoute: ApiIssuesIdReactionsRoute,
  ApiIssuesIdSubscribeRoute: ApiIssuesIdSubscribeRoute,
  ApiIssuesIdSubscribersRoute: ApiIssuesIdSubscribersRoute,
  ApiIssuesIdTimelineRoute: ApiIssuesIdTimelineRoute,
  ApiIssuesIdUnsubscribeRoute: ApiIssuesIdUnsubscribeRoute,
  ApiIssuesIdUsageRoute: ApiIssuesIdUsageRoute,
}

const ApiIssuesIdRouteWithChildren = ApiIssuesIdRoute._addFileChildren(
  ApiIssuesIdRouteChildren,
)

interface ApiIssuesRouteChildren {
  ApiIssuesIdRoute: typeof ApiIssuesIdRouteWithChildren
  ApiIssuesChildProgressRoute: typeof ApiIssuesChildProgressRoute
  ApiIssuesSearchRoute: typeof ApiIssuesSearchRoute
}

const ApiIssuesRouteChildren: ApiIssuesRouteChildren = {
  ApiIssuesIdRoute: ApiIssuesIdRouteWithChildren,
  ApiIssuesChildProgressRoute: ApiIssuesChildProgressRoute,
  ApiIssuesSearchRoute: ApiIssuesSearchRoute,
}

const ApiIssuesRouteWithChildren = ApiIssuesRoute._addFileChildren(
  ApiIssuesRouteChildren,
)

interface ApiSkillsRouteChildren {
  ApiSkillsIdRoute: typeof ApiSkillsIdRoute
  ApiSkillsImportRoute: typeof ApiSkillsImportRoute
  ApiSkillsPreviewRoute: typeof ApiSkillsPreviewRoute
  ApiSkillsSearchRoute: typeof ApiSkillsSearchRoute
}

const ApiSkillsRouteChildren: ApiSkillsRouteChildren = {
  ApiSkillsIdRoute: ApiSkillsIdRoute,
  ApiSkillsImportRoute: ApiSkillsImportRoute,
  ApiSkillsPreviewRoute: ApiSkillsPreviewRoute,
  ApiSkillsSearchRoute: ApiSkillsSearchRoute,
}

const ApiSkillsRouteWithChildren = ApiSkillsRoute._addFileChildren(
  ApiSkillsRouteChildren,
)

interface ApiWorkspacesIdInvitationsRouteChildren {
  ApiWorkspacesIdInvitationsInvitationIdRoute: typeof ApiWorkspacesIdInvitationsInvitationIdRoute
}

const ApiWorkspacesIdInvitationsRouteChildren: ApiWorkspacesIdInvitationsRouteChildren =
  {
    ApiWorkspacesIdInvitationsInvitationIdRoute:
      ApiWorkspacesIdInvitationsInvitationIdRoute,
  }

const ApiWorkspacesIdInvitationsRouteWithChildren =
  ApiWorkspacesIdInvitationsRoute._addFileChildren(
    ApiWorkspacesIdInvitationsRouteChildren,
  )

interface ApiWorkspacesIdMembersRouteChildren {
  ApiWorkspacesIdMembersMemberIdRoute: typeof ApiWorkspacesIdMembersMemberIdRoute
}

const ApiWorkspacesIdMembersRouteChildren: ApiWorkspacesIdMembersRouteChildren =
  {
    ApiWorkspacesIdMembersMemberIdRoute: ApiWorkspacesIdMembersMemberIdRoute,
  }

const ApiWorkspacesIdMembersRouteWithChildren =
  ApiWorkspacesIdMembersRoute._addFileChildren(
    ApiWorkspacesIdMembersRouteChildren,
  )

interface ApiWorkspacesIdRouteChildren {
  ApiWorkspacesIdInvitationsRoute: typeof ApiWorkspacesIdInvitationsRouteWithChildren
  ApiWorkspacesIdMembersRoute: typeof ApiWorkspacesIdMembersRouteWithChildren
}

const ApiWorkspacesIdRouteChildren: ApiWorkspacesIdRouteChildren = {
  ApiWorkspacesIdInvitationsRoute: ApiWorkspacesIdInvitationsRouteWithChildren,
  ApiWorkspacesIdMembersRoute: ApiWorkspacesIdMembersRouteWithChildren,
}

const ApiWorkspacesIdRouteWithChildren = ApiWorkspacesIdRoute._addFileChildren(
  ApiWorkspacesIdRouteChildren,
)

interface ApiWorkspacesRouteChildren {
  ApiWorkspacesIdRoute: typeof ApiWorkspacesIdRouteWithChildren
}

const ApiWorkspacesRouteChildren: ApiWorkspacesRouteChildren = {
  ApiWorkspacesIdRoute: ApiWorkspacesIdRouteWithChildren,
}

const ApiWorkspacesRouteWithChildren = ApiWorkspacesRoute._addFileChildren(
  ApiWorkspacesRouteChildren,
)

interface ApiChatThreadsIdRouteChildren {
  ApiChatThreadsIdToolApprovalRoute: typeof ApiChatThreadsIdToolApprovalRoute
}

const ApiChatThreadsIdRouteChildren: ApiChatThreadsIdRouteChildren = {
  ApiChatThreadsIdToolApprovalRoute: ApiChatThreadsIdToolApprovalRoute,
}

const ApiChatThreadsIdRouteWithChildren =
  ApiChatThreadsIdRoute._addFileChildren(ApiChatThreadsIdRouteChildren)

interface ApiChatThreadsRouteChildren {
  ApiChatThreadsIdRoute: typeof ApiChatThreadsIdRouteWithChildren
}

const ApiChatThreadsRouteChildren: ApiChatThreadsRouteChildren = {
  ApiChatThreadsIdRoute: ApiChatThreadsIdRouteWithChildren,
}

const ApiChatThreadsRouteWithChildren = ApiChatThreadsRoute._addFileChildren(
  ApiChatThreadsRouteChildren,
)

interface ApiCommentsIdRouteChildren {
  ApiCommentsIdReactionsRoute: typeof ApiCommentsIdReactionsRoute
}

const ApiCommentsIdRouteChildren: ApiCommentsIdRouteChildren = {
  ApiCommentsIdReactionsRoute: ApiCommentsIdReactionsRoute,
}

const ApiCommentsIdRouteWithChildren = ApiCommentsIdRoute._addFileChildren(
  ApiCommentsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAgentsRoute: ApiAgentsRouteWithChildren,
  ApiBootstrapRoute: ApiBootstrapRoute,
  ApiConnectionsRoute: ApiConnectionsRouteWithChildren,
  ApiDebugStreamRoute: ApiDebugStreamRoute,
  ApiInboxRoute: ApiInboxRouteWithChildren,
  ApiInvitationsRoute: ApiInvitationsRouteWithChildren,
  ApiIssuesRoute: ApiIssuesRouteWithChildren,
  ApiMeRoute: ApiMeRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiRuntimesRoute: ApiRuntimesRoute,
  ApiSkillsRoute: ApiSkillsRouteWithChildren,
  ApiWorkspacesRoute: ApiWorkspacesRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatThreadsRoute: ApiChatThreadsRouteWithChildren,
  ApiCommentsIdRoute: ApiCommentsIdRouteWithChildren,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubInstallRoute: ApiGithubInstallRoute,
  ApiGithubSetupRoute: ApiGithubSetupRoute,
  ApiInternalCapabilitySyncRoute: ApiInternalCapabilitySyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
